In [1]:
import os 
import requests

pdf_path = "human-nutrition-text.pdf"

if not os.path.exists(pdf_path):
    print("File does not exist, downloading...")

    url = "https://pressbooks.oer.hawaii.edu/humannutrition2/open/download?type=pdf"

    filename = pdf_path

    response = requests.get(url)

    if response.status_code == 200:
        with open(filename, "wb") as f:
            f.write(response.content)
        print(f"The file was downloaded successfully as {filename}")

    else:
        print("Failed to download the file")

In [2]:
import fitz
from tqdm.auto import tqdm

def text_formatter(text):
    cleaned_text = text.replace("\n", " ").strip()

    return cleaned_text

def open_and_read_pdf(pdf_path):
    doc = fitz.open(pdf_path)

    pages_and_texts = []

    for page_number, page in tqdm(enumerate(doc)):
        text = page.get_text()
        text = text_formatter(text)

        pages_and_texts.append({
            "page_number": page_number - 41,
            "page_char_count": len(text),
            "page_word_count": len(text.split(" ")),
            "page_sentence_count_raw": len(text.split(". ")),
            "page_token_count": len(text) / 4,
            "text": text
        })

    return pages_and_texts

pages_and_texts = open_and_read_pdf(pdf_path=pdf_path)
pages_and_texts[:2]

0it [00:00, ?it/s]

[{'page_number': -41,
  'page_char_count': 29,
  'page_word_count': 4,
  'page_sentence_count_raw': 1,
  'page_token_count': 7.25,
  'text': 'Human Nutrition: 2020 Edition'},
 {'page_number': -40,
  'page_char_count': 0,
  'page_word_count': 1,
  'page_sentence_count_raw': 1,
  'page_token_count': 0.0,
  'text': ''}]

In [3]:
import pandas as pd

df = pd.DataFrame(pages_and_texts)

df.head()

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,text
0,-41,29,4,1,7.25,Human Nutrition: 2020 Edition
1,-40,0,1,1,0.00,
2,-39,320,54,1,80.00,Human Nutrition: 2020 Edition UNIVERSITY OF ...
3,-38,212,32,1,53.00,Human Nutrition: 2020 Edition by University of...
4,-37,797,147,3,199.25,Contents Preface University of Hawai‘i at Mā...

In [4]:
df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count
count,1208.00,1208.00,1208.00,1208.00,1208.00
mean,562.50,1148.00,199.50,10.52,287.00
std,348.86,560.38,95.83,6.55,140.10
min,-41.00,0.00,1.00,1.00,0.00
25%,260.75,762.00,134.00,5.00,190.50
50%,562.50,1231.50,216.00,10.00,307.88
75%,864.25,1603.50,272.00,15.00,400.88
max,1166.00,2308.00,430.00,39.00,577.00

In [5]:
from spacy.lang.en import English

nlp = English()

nlp.add_pipe("sentencizer")

doc = nlp("This is some sentence. This is another sentence. And this is another one.")

list(doc.sents)

[This is some sentence., This is another sentence., And this is another one.]

In [6]:
pages_and_texts[0]

{'page_number': -41,
 'page_char_count': 29,
 'page_word_count': 4,
 'page_sentence_count_raw': 1,
 'page_token_count': 7.25,
 'text': 'Human Nutrition: 2020 Edition'}

In [7]:
for item in tqdm(pages_and_texts):
    item["sentences"] = list(nlp(item["text"]).sents)

    item["sentences"] = [str(sentence) for sentence in item["sentences"]]

    item["page_sentence_count_spacy"] = len(item["sentences"])

  0%|          | 0/1208 [00:00<?, ?it/s]

In [8]:
import random

random.sample(pages_and_texts, k=3)

[{'page_number': 36,
  'page_char_count': 1533,
  'page_word_count': 254,
  'page_sentence_count_raw': 25,
  'page_token_count': 383.25,
  'text': 'Experimental test. Coindet administered iodine tincture orally to  his patients with goiter.  Interpret results. Coindet’s iodine treatment was successful.    Hypothesis. French chemist Chatin proposed that the low iodine  content in food and water in certain areas far away from the ocean  was the primary cause of goiter, and renounced the theory that  goiter was the result of poor hygiene.  Experimental test. In the late 1860s the program, “The stamping- out of goiter,” started with people in several villages in France being  given iodine tablets.  Results. The program was effective and 80 percent of goitrous  children were cured.    Hypothesis. In 1918, Swiss doctor Bayard proposed iodizing salt as  a good way to treat areas endemic with goiter.  Experimental test. Iodized salt was transported by mules to a  small village at the base of the Matterhorn where more than 75  percent of school children were goitrous. It was given to families to  use for six months.  Results. The iodized salt was beneficial in treating goiter in this  remote population.    Experimental test. Physician David Marine conducted the first  experiment of treating goiter with iodized salt in America in Akron,  Ohio.2  of Nutrition, 138(11), 2060–63. http://jn.nutrition.org/ content/138/11/2060.full  2. Carpenter, K.J. (2005). David Marine and the Problem of  Goiter. Journal of Nutrition, 135(4),  675–80. http://jn.nutrition.org/content/135/4/ 675.full?sid=d06fdd35-566f -42a2-a3fd- efbe0736b7ba  36  |  Research and the Scientific Method',
  'sentences': ['Experimental test.',
   'Coindet administered iodine tincture orally to  his patients with goiter.',
   ' Interpret results.',
   'Coindet’s iodine treatment was successful.',
   '   Hypothesis.',
   'French chemist Chatin proposed that the low iodine  content in food and water in certain areas far away from the ocean  was the primary cause of goiter, and renounced the theory that  goiter was the result of poor hygiene.',
   ' Experimental test.',
   'In the late 1860s the program, “The stamping- out of goiter,” started with people in several villages in France being  given iodine tablets.',
   ' Results.',
   'The program was effective and 80 percent of goitrous  children were cured.',
   '   Hypothesis.',
   'In 1918, Swiss doctor Bayard proposed iodizing salt as  a good way to treat areas endemic with goiter.',
   ' Experimental test.',
   'Iodized salt was transported by mules to a  small village at the base of the Matterhorn where more than 75  percent of school children were goitrous.',
   'It was given to families to  use for six months.',
   ' Results.',
   'The iodized salt was beneficial in treating goiter in this  remote population.',
   '   Experimental test.',
   'Physician David Marine conducted the first  experiment of treating goiter with iodized salt in America in Akron,  Ohio.2  of Nutrition, 138(11), 2060–63.',
   'http://jn.nutrition.org/ content/138/11/2060.full  2.',
   'Carpenter, K.J. (2005).',
   'David Marine and the Problem of  Goiter.',
   'Journal of Nutrition, 135(4),  675–80.',
   'http://jn.nutrition.org/content/135/4/ 675.full?sid=d06fdd35-566f -42a2-a3fd- efbe0736b7ba  36  |  Research and the Scientific Method'],
  'page_sentence_count_spacy': 24},
 {'page_number': 686,
  'page_char_count': 1395,
  'page_word_count': 247,
  'page_sentence_count_raw': 18,
  'page_token_count': 348.75,
  'text': 'Chromium  UNIVERSITY OF HAWAI‘I AT MĀNOA FOOD SCIENCE AND HUMAN  NUTRITION PROGRAM AND HUMAN NUTRITION PROGRAM  The functioning of chromium in the body is less understood than  that of most other minerals. It enhances the actions of insulin so it  plays a role in carbohydrate, fat, and protein metabolism. Currently,  the results of scientific studies evaluating the usefulness of  chromium supplementation in preventing and treating Type 2  diabetes are largely inconclusive. More research is needed to better  determine if chromium is helpful in treating certain chronic  diseases and, if so, at what doses. If a deficiency of chromium occurs  in the body, signs and symptoms include weight loss, peripheral  neuropathy, elevated plasma glucose concentrations or impaired  glucose use, and high plasma free fatty acid concentrations.  Although toxicity of the mineral is a low risk in humans, it can cause  DNA damage, organ damage, and renal problems. Tissues that are  high in chromium include the liver, spleen, and bone.1  Dietary Reference Intakes for Chromium  The recommended intake for chromium is 35 mcg per day for adult  males and 25 mcg per day for adult females. There is insufficient  evidence to establish an UL for chromium.    1. Gropper, S. A. S., Smith, J. L., & Carr, T. P. (2018).  Advanced nutrition and human metabolism. Boston, MA:  Cengage Learning.  686  |  Chromium',
  'sentences': ['Chromium  UNIVERSITY OF HAWAI‘I AT MĀNOA FOOD SCIENCE AND HUMAN  NUTRITION PROGRAM AND HUMAN NUTRITION PROGRAM  The functioning of chromium in the body is less understood than  that of most other minerals.',
   'It enhances the actions of insulin so it  plays a role in carbohydrate, fat, and protein metabolism.',
   'Currently,  the results of scientific studies evaluating the usefulness of  chromium supplementation in preventing and treating Type 2  diabetes are largely inconclusive.',
   'More research is needed to better  determine if chromium is helpful in treating certain chronic  diseases and, if so, at what doses.',
   'If a deficiency of chromium occurs  in the body, signs and symptoms include weight loss, peripheral  neuropathy, elevated plasma glucose concentrations or impaired  glucose use, and high plasma free fatty acid concentrations.',
   ' Although toxicity of the mineral is a low risk in humans, it can cause  DNA damage, organ damage, and renal problems.',
   'Tissues that are  high in chromium include the liver, spleen, and bone.1  Dietary Reference Intakes for Chromium  The recommended intake for chromium is 35 mcg per day for adult  males and 25 mcg per day for adult females.',
   'There is insufficient  evidence to establish an UL for chromium.',
   '   1.',
   'Gropper, S. A. S., Smith, J. L., & Carr, T. P. (2018).',
   ' Advanced nutrition and human metabolism.',
   'Boston, MA:  Cengage Learning.',
   ' 686  |  Chromium'],
  'page_sentence_count_spacy': 13},
 {'page_number': 466,
  'page_char_count': 2011,
  'page_word_count': 338,
  'page_sentence_count_raw': 13,
  'page_token_count': 502.75,
  'text': 'molecules of carbon dioxide. The energy obtained from the  breaking of chemical bonds in the citric acid cycle is transformed  into two more ATP molecules (or equivalents thereof) and high  energy electrons that are carried by the molecules, nicotinamide  adenine dinucleotide (NADH) and flavin adenine dinucleotide  (FADH2). NADH and FADH2 carry the electrons to the inner  membrane in the mitochondria where the third stage of energy  release takes place, in what is called the electron transport chain. In  this metabolic pathway a sequential transfer of electrons between  multiple proteins occurs and ATP is synthesized. The entire process  of nutrient catabolism is chemically similar to burning, as carbon  and hydrogen atoms are  combusted (oxidized) producing carbon  dioxide, water, and heat. However, the stepwise chemical reactions  in nutrient catabolism pathways slow the oxidation of carbon atoms  so that much of the energy is captured and not all transformed into  heat and light. Complete nutrient catabolism is between 30 and 40  percent efficient, and some of the energy is therefore released as  heat. Heat is a vital product of nutrient catabolism and is involved in  maintaining body temperature. If cells were too efficient at trapping  nutrient energy into ATP, humans would not last to the next meal, as  they would die of hypothermia (excessively low body temperature).  Anabolism: The Building  The energy released by catabolic pathways powers anabolic  pathways in the building of macromolecules such as the proteins  RNA and DNA, and even entire new cells and tissues. Anabolic  pathways are required to build new tissue, such as muscle, after  prolonged exercise or the remodeling of bone tissue, a process  involving both catabolic and anabolic pathways. Anabolic pathways  also build energy-storage molecules, such as Glycogen and  triglycerides. Intermediates in the catabolic pathways of energy  metabolism are sometimes diverted from ATP production and used  466  |  The Atom',
  'sentences': ['molecules of carbon dioxide.',
   'The energy obtained from the  breaking of chemical bonds in the citric acid cycle is transformed  into two more ATP molecules (or equivalents thereof) and high  energy electrons that are carried by the molecules, nicotinamide  adenine dinucleotide (NADH) and flavin adenine dinucleotide  (FADH2).',
   'NADH and FADH2 carry the electrons to the inner  membrane in the mitochondria where the third stage of energy  release takes place, in what is called the electron transport chain.',
   'In  this metabolic pathway a sequential transfer of electrons between  multiple proteins occurs and ATP is synthesized.',
   'The entire process  of nutrient catabolism is chemically similar to burning, as carbon  and hydrogen atoms are  combusted (oxidized) producing carbon  dioxide, water, and heat.',
   'However, the stepwise chemical reactions  in nutrient catabolism pathways slow the oxidation of carbon atoms  so that much of the energy is captured and not all transformed into  heat and light.',
   'Complete nutrient catabolism is between 30 and 40  percent efficient, and some of the energy is therefore released as  heat.',
   'Heat is a vital product of nutrient catabolism and is involved in  maintaining body temperature.',
   'If cells were too efficient at trapping  nutrient energy into ATP, humans would not last to the next meal, as  they would die of hypothermia (excessively low body temperature).',
   ' Anabolism: The Building  The energy released by catabolic pathways powers anabolic  pathways in the building of macromolecules such as the proteins  RNA and DNA, and even entire new cells and tissues.',
   'Anabolic  pathways are required to build new tissue, such as muscle, after  prolonged exercise or the remodeling of bone tissue, a process  involving both catabolic and anabolic pathways.',
   'Anabolic pathways  also build energy-storage molecules, such as Glycogen and  triglycerides.',
   'Intermediates in the catabolic pathways of energy  metabolism are sometimes diverted from ATP production and used  466  |  The Atom'],
  'page_sentence_count_spacy': 13}]

In [9]:
df = pd.DataFrame(pages_and_texts)

df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,page_sentence_count_spacy
count,1208.00,1208.00,1208.00,1208.00,1208.00,1208.00
mean,562.50,1148.00,199.50,10.52,287.00,10.32
std,348.86,560.38,95.83,6.55,140.10,6.30
min,-41.00,0.00,1.00,1.00,0.00,0.00
25%,260.75,762.00,134.00,5.00,190.50,5.00
50%,562.50,1231.50,216.00,10.00,307.88,10.00
75%,864.25,1603.50,272.00,15.00,400.88,15.00
max,1166.00,2308.00,430.00,39.00,577.00,28.00

In [10]:
num_sentence_chunk_size = 10

def split_list(input_list, slice_size=num_sentence_chunk_size):
    return [input_list[i:i+slice_size] for i in range(0, len(input_list), slice_size)]

test_list = list(range(29))
split_list(test_list)

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9],
 [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
 [20, 21, 22, 23, 24, 25, 26, 27, 28]]

In [11]:
for item in tqdm(pages_and_texts):
    item["sentence_chunks"] = split_list(
        input_list=item["sentences"],
        slice_size=num_sentence_chunk_size
    )

    item["num_chunks"] = len(item["sentence_chunks"])

  0%|          | 0/1208 [00:00<?, ?it/s]

In [12]:
random.sample(pages_and_texts, k=3)

[{'page_number': 1053,
  'page_char_count': 1649,
  'page_word_count': 300,
  'page_sentence_count_raw': 16,
  'page_token_count': 412.25,
  'text': 'The benefits of this kind of diet include an emphasis on whole,  unprocessed foods and a de-emphasis of refined carbohydrates,  such as white flour, white bread, and white sugar. However, there  are a number of downsides. Typically, the first two weeks allow  for only 20 grams of carbs per day, which can be dangerously low.  In addition, dieters using the low-carb approach tend to consume  twice as many saturated fats as people on a diet high in healthy  carbohydrates. Low-carb diets are also associated with a higher  energy intake, and the notion that “calories don’t count,” which  is prevalent in this kind of diet, is not supported by scientific  evidence.8  The Macrobiotic Diet  The macrobiotic diet is part of a health and wellness regimen based  in Eastern philosophy. It combines certain tenets of Zen Buddhism  with a vegetarian diet and supports a balance of the oppositional  forces of yin and yang. Foods are paired based on their so-called  yin or yang characteristics. Yin foods are thought to be sweet, cold,  and passive, while yang foods are considered to be salty, hot, and  aggressive.  Whole grains make up about 50 percent of the calories consumed  and are believed to have the best balance of yin and yang. Raw  and cooked vegetables comprise about 30 percent of the diet and  include kale, cabbage, collards, bok choy, and broccoli on a daily  8. Steele V. Health and Nutritional Effects of Popular Diets.  Kellogg Nutrition Symposium, The Team of Registered  Dietitians & Nutrition Professionals at Kellogg Canada  Inc. Insert to Canadian Journal of Dietetic Practice and  Research 64, no. 3.  Comparing Diets  |  1053',
  'sentences': ['The benefits of this kind of diet include an emphasis on whole,  unprocessed foods and a de-emphasis of refined carbohydrates,  such as white flour, white bread, and white sugar.',
   'However, there  are a number of downsides.',
   'Typically, the first two weeks allow  for only 20 grams of carbs per day, which can be dangerously low.',
   ' In addition, dieters using the low-carb approach tend to consume  twice as many saturated fats as people on a diet high in healthy  carbohydrates.',
   'Low-carb diets are also associated with a higher  energy intake, and the notion that “calories don’t count,” which  is prevalent in this kind of diet, is not supported by scientific  evidence.8  The Macrobiotic Diet  The macrobiotic diet is part of a health and wellness regimen based  in Eastern philosophy.',
   'It combines certain tenets of Zen Buddhism  with a vegetarian diet and supports a balance of the oppositional  forces of yin and yang.',
   'Foods are paired based on their so-called  yin or yang characteristics.',
   'Yin foods are thought to be sweet, cold,  and passive, while yang foods are considered to be salty, hot, and  aggressive.',
   ' Whole grains make up about 50 percent of the calories consumed  and are believed to have the best balance of yin and yang.',
   'Raw  and cooked vegetables comprise about 30 percent of the diet and  include kale, cabbage, collards, bok choy, and broccoli on a daily  8.',
   'Steele V. Health and Nutritional Effects of Popular Diets.',
   ' Kellogg Nutrition Symposium, The Team of Registered  Dietitians & Nutrition Professionals at Kellogg Canada  Inc. Insert to Canadian Journal of Dietetic Practice and  Research 64, no.',
   '3.',
   ' Comparing Diets  |  1053'],
  'page_sentence_count_spacy': 14,
  'sentence_chunks': [['The benefits of this kind of diet include an emphasis on whole,  unprocessed foods and a de-emphasis of refined carbohydrates,  such as white flour, white bread, and white sugar.',
    'However, there  are a number of downsides.',
    'Typically, the first two weeks allow  for only 20 grams of carbs per day, which can be dangerously low.',
    ' In addition, dieters using the low-carb approach tend to consume  twice as many saturated fats as people on a diet high in healthy  carbohydrates.',
    'Low-carb diets are also associated with a higher  energy intake, and the notion that “calories don’t count,” which  is prevalent in this kind of diet, is not supported by scientific  evidence.8  The Macrobiotic Diet  The macrobiotic diet is part of a health and wellness regimen based  in Eastern philosophy.',
    'It combines certain tenets of Zen Buddhism  with a vegetarian diet and supports a balance of the oppositional  forces of yin and yang.',
    'Foods are paired based on their so-called  yin or yang characteristics.',
    'Yin foods are thought to be sweet, cold,  and passive, while yang foods are considered to be salty, hot, and  aggressive.',
    ' Whole grains make up about 50 percent of the calories consumed  and are believed to have the best balance of yin and yang.',
    'Raw  and cooked vegetables comprise about 30 percent of the diet and  include kale, cabbage, collards, bok choy, and broccoli on a daily  8.'],
   ['Steele V. Health and Nutritional Effects of Popular Diets.',
    ' Kellogg Nutrition Symposium, The Team of Registered  Dietitians & Nutrition Professionals at Kellogg Canada  Inc. Insert to Canadian Journal of Dietetic Practice and  Research 64, no.',
    '3.',
    ' Comparing Diets  |  1053']],
  'num_chunks': 2},
 {'page_number': 502,
  'page_char_count': 1837,
  'page_word_count': 287,
  'page_sentence_count_raw': 23,
  'page_token_count': 459.25,
  'text': 'keeping it off for at least one year.1 Results from lifestyle  intervention studies suggest fewer than 20 percent of participants  are successful at weight loss. An evaluation of successful weight  loss, involving more than fourteen thousand participants published  in the November 2011 issue of the International Journal of Obesity  estimates that more than one in six Americans (17 percent) who  were overweight or obese were successful in achieving long-term  weight loss.2 However, these numbers are on the high end because  many similar studies report fewer than 10 percent of participants as  successful in weight loss.  The National Weight Control Registry (NWCR) tracks over ten  thousand people who have been successful in losing at least 30  pounds and maintaining this weight loss for at least one year. Their  research findings are that 98 percent of participants in the registry  modified their food intake and 94 percent increased their physical  activity (mainly walking).3  Although there are a great variety of approaches taken by NWCR  members to achieve successful weight loss, most report that their  approach involved adhering to a low-calorie, low-fat diet and doing  1. Wing RR, Hill JO. (2001).  Successful Weight Loss  Maintenance. Annual Review of Nutrition, 21, 323–41.  http://www.ncbi.nlm.nih.gov/pubmed/ 11375440?dopt=Abstract. Accessed September 22, 2017.  2. Kraschnewski JL, Boan J, et al. (2010). Long-Term Weight  Loss Maintenance in the United States. International  Journal of Obesity, 34(11),1644–54.  http://www.ncbi.nlm.nih.gov/pubmed/20479763.  Accessed September 22, 2017.  3. Research Findings. The National Weight Control  Registry. http://www.nwcr.ws/Research/default.htm.  Accessed September 22, 2017.  502  |  Dietary, Behavioral, and Physical Activity Recommendations for Weight Management',
  'sentences': ['keeping it off for at least one year.1 Results from lifestyle  intervention studies suggest fewer than 20 percent of participants  are successful at weight loss.',
   'An evaluation of successful weight  loss, involving more than fourteen thousand participants published  in the November 2011 issue of the International Journal of Obesity  estimates that more than one in six Americans (17 percent) who  were overweight or obese were successful in achieving long-term  weight loss.2 However, these numbers are on the high end because  many similar studies report fewer than 10 percent of participants as  successful in weight loss.',
   ' The National Weight Control Registry (NWCR) tracks over ten  thousand people who have been successful in losing at least 30  pounds and maintaining this weight loss for at least one year.',
   'Their  research findings are that 98 percent of participants in the registry  modified their food intake and 94 percent increased their physical  activity (mainly walking).3  Although there are a great variety of approaches taken by NWCR  members to achieve successful weight loss, most report that their  approach involved adhering to a low-calorie, low-fat diet and doing  1.',
   'Wing RR, Hill JO. (',
   '2001).',
   ' Successful Weight Loss  Maintenance.',
   'Annual Review of Nutrition, 21, 323–41.',
   ' http://www.ncbi.nlm.nih.gov/pubmed/ 11375440?dopt=Abstract.',
   'Accessed September 22, 2017.',
   ' 2.',
   'Kraschnewski JL, Boan J, et al. (',
   '2010).',
   'Long-Term Weight  Loss Maintenance in the United States.',
   'International  Journal of Obesity, 34(11),1644–54.',
   ' http://www.ncbi.nlm.nih.gov/pubmed/20479763.',
   ' Accessed September 22, 2017.',
   ' 3.',
   'Research Findings.',
   'The National Weight Control  Registry.',
   'http://www.nwcr.ws/Research/default.htm.',
   ' Accessed September 22, 2017.',
   ' 502  |  Dietary, Behavioral, and Physical Activity Recommendations for Weight Management'],
  'page_sentence_count_spacy': 23,
  'sentence_chunks': [['keeping it off for at least one year.1 Results from lifestyle  intervention studies suggest fewer than 20 percent of participants  are successful at weight loss.',
    'An evaluation of successful weight  loss, involving more than fourteen thousand participants published  in the November 2011 issue of the International Journal of Obesity  estimates that more than one in six Americans (17 percent) who  were overweight or obese were successful in achieving long-term  weight loss.2 However, these numbers are on the high end because  many similar studies report fewer than 10 percent of participants as  successful in weight loss.',
    ' The National Weight Control Registry (NWCR) tracks over ten  thousand people who have been successful in losing at least 30  pounds and maintaining this weight loss for at least one year.',
    'Their  research findings are that 98 percent of participants in the registry  modified their food intake and 94 percent increased their physical  activity (mainly walking).3  Although there are a great variety of approaches taken by NWCR  members to achieve successful weight loss, most report that their  approach involved adhering to a low-calorie, low-fat diet and doing  1.',
    'Wing RR, Hill JO. (',
    '2001).',
    ' Successful Weight Loss  Maintenance.',
    'Annual Review of Nutrition, 21, 323–41.',
    ' http://www.ncbi.nlm.nih.gov/pubmed/ 11375440?dopt=Abstract.',
    'Accessed September 22, 2017.'],
   [' 2.',
    'Kraschnewski JL, Boan J, et al. (',
    '2010).',
    'Long-Term Weight  Loss Maintenance in the United States.',
    'International  Journal of Obesity, 34(11),1644–54.',
    ' http://www.ncbi.nlm.nih.gov/pubmed/20479763.',
    ' Accessed September 22, 2017.',
    ' 3.',
    'Research Findings.',
    'The National Weight Control  Registry.'],
   ['http://www.nwcr.ws/Research/default.htm.',
    ' Accessed September 22, 2017.',
    ' 502  |  Dietary, Behavioral, and Physical Activity Recommendations for Weight Management']],
  'num_chunks': 3},
 {'page_number': -10,
  'page_char_count': 521,
  'page_word_count': 99,
  'page_sentence_count_raw': 4,
  'page_token_count': 130.25,
  'text': 'Cheryl Gibby  Cheryl Gibby was born and raised in Hawai‘i and is a wife and  mother of three. She received her BA, MS in Nutritional Sciences,  and PhD in Nutrition from the University of Hawai‘i at Mānoa. She  has served as an instructor for the introductory Nutrition course  at the University of Hawai‘i at Mānoa, and her research interests  include infant and child health, dental and bone health, mobile  health  interventions,  school  nutrition  policies,  and  online  education.  xxxii  |  About the Contributors',
  'sentences': ['Cheryl Gibby  Cheryl Gibby was born and raised in Hawai‘i and is a wife and  mother of three.',
   'She received her BA, MS in Nutritional Sciences,  and PhD in Nutrition from the University of Hawai‘i at Mānoa.',
   'She  has served as an instructor for the introductory Nutrition course  at the University of Hawai‘i at Mānoa, and her research interests  include infant and child health, dental and bone health, mobile  health  interventions,  school  nutrition  policies,  and  online  education.',
   ' xxxii  |  About the Contributors'],
  'page_sentence_count_spacy': 4,
  'sentence_chunks': [['Cheryl Gibby  Cheryl Gibby was born and raised in Hawai‘i and is a wife and  mother of three.',
    'She received her BA, MS in Nutritional Sciences,  and PhD in Nutrition from the University of Hawai‘i at Mānoa.',
    'She  has served as an instructor for the introductory Nutrition course  at the University of Hawai‘i at Mānoa, and her research interests  include infant and child health, dental and bone health, mobile  health  interventions,  school  nutrition  policies,  and  online  education.',
    ' xxxii  |  About the Contributors']],
  'num_chunks': 1}]

In [13]:
df = pd.DataFrame(pages_and_texts)

df.describe().round(2)

,page_number,page_char_count,page_word_count,page_sentence_count_raw,page_token_count,page_sentence_count_spacy,num_chunks
count,1208.00,1208.00,1208.00,1208.00,1208.00,1208.00,1208.00
mean,562.50,1148.00,199.50,10.52,287.00,10.32,1.53
std,348.86,560.38,95.83,6.55,140.10,6.30,0.64
min,-41.00,0.00,1.00,1.00,0.00,0.00,0.00
25%,260.75,762.00,134.00,5.00,190.50,5.00,1.00
50%,562.50,1231.50,216.00,10.00,307.88,10.00,1.00
75%,864.25,1603.50,272.00,15.00,400.88,15.00,2.00
max,1166.00,2308.00,430.00,39.00,577.00,28.00,3.00

In [19]:
import re

pages_and_chunks = []
for item in tqdm(pages_and_texts):
    for chunk in item["sentence_chunks"]:
        chunk_dict = {}

        chunk_dict["page_number"] = item["page_number"]

        joined_sentence_chunk = "".join(chunk).replace("  ", " ").strip()
        joined_sentence_chunk = re.sub(r'\.([A-Z])', r'. \1', joined_sentence_chunk)


        chunk_dict["sentence_chunk"] = joined_sentence_chunk

        chunk_dict["chunk_char_count"] = len(joined_sentence_chunk)
        chunk_dict["chunk_word_count"] = len([word for word in joined_sentence_chunk.split(" ")])
        chunk_dict["chunk_token_count"] = len(joined_sentence_chunk) / 4

        pages_and_chunks.append(chunk_dict)

len(pages_and_chunks)

  0%|          | 0/1208 [00:00<?, ?it/s]

1843

In [20]:
df = pd.DataFrame(pages_and_chunks)

df.describe().round(2)

       page_number  chunk_char_count  chunk_word_count  chunk_token_count
count      1843.00           1843.00           1843.00            1843.00
mean        583.38            734.10            112.74             183.52
std         347.79            447.51             71.24             111.88
min         -41.00             12.00              3.00               3.00
25%         280.50            315.00             45.00              78.75
50%         586.00            745.00            115.00             186.25
75%         890.00           1118.00            173.00             279.50
max        1166.00           1830.00            297.00             457.50

In [21]:
df.head()

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count
0,-41,Human Nutrition: 2020 Edition,29,4,7.25
1,-39,Human Nutrition: 2020 Edition UNIVERSITY OF HA...,308,42,77.00
2,-38,Human Nutrition: 2020 Edition by University of...,210,30,52.50
3,-37,Contents Preface University of Hawai‘i at Māno...,766,116,191.50
4,-36,Lifestyles and Nutrition University of Hawai‘i...,941,144,235.25

In [31]:
min_token_length = 30
for row in df[df["chunk_token_count"] <= min_token_length].sample(5).iterrows():
    print(f'Chunk token count: {row[1]["chunk_token_count"]} | Text: {row[1]["sentence_chunk"]}')

Chunk token count: 17.5 | Text: The Obesity Myth. Gotham Books. Calories In Versus Calories Out | 1069
Chunk token count: 11.25 | Text: Accessed March 17, 2011. 212 | Water Concerns
Chunk token count: 21.0 | Text: Updated September 2003. Accessed November 28,2017. Discovering Nutrition Facts | 735
Chunk token count: 29.0 | Text: 2010). EH. Net Encyclopedia. http://eh.net/?s=History+of+Food+and+Drug+Regulatio Protecting the Public Health | 1011
Chunk token count: 26.25 | Text: Snowdon W, Osborn T. (2003). Coconut: It’s role in health. Secretariat of the Pacific. 292 | Introduction

In [32]:
pages_and_chunks_over_min_token_len = df[df["chunk_token_count"] > min_token_length].to_dict(orient="records")
pages_and_chunks_over_min_token_len[:2]

[{'page_number': -39,
  'sentence_chunk': 'Human Nutrition: 2020 Edition UNIVERSITY OF HAWAI‘I AT MĀNOA FOOD SCIENCE AND HUMAN NUTRITION PROGRAM ALAN TITCHENAL, SKYLAR HARA, NOEMI ARCEO CAACBAY, WILLIAM MEINKE-LAU, YA-YUN YANG, MARIE KAINOA FIALKOWSKI REVILLA, JENNIFER DRAPER, GEMADY LANGFELDER, CHERYL GIBBY, CHYNA NICOLE CHUN, AND ALLISON CALABRESE',
  'chunk_char_count': 308,
  'chunk_word_count': 42,
  'chunk_token_count': 77.0},
 {'page_number': -38,
  'sentence_chunk': 'Human Nutrition: 2020 Edition by University of Hawai‘i at Mānoa Food Science and Human Nutrition Program is licensed under a Creative Commons Attribution 4.0 International License, except where otherwise noted.',
  'chunk_char_count': 210,
  'chunk_word_count': 30,
  'chunk_token_count': 52.5}]

In [33]:
from sentence_transformers import SentenceTransformer

embedding_model = SentenceTransformer(
    model_name_or_path="all-mpnet-base-v2",
    device="mps"
)

sentences = [
    "I would like to play football one day.",
    "My favourite player is Lionel Messi.",
    "It's raining"
]

embeddings = embedding_model.encode(sentences)
embeddings_dict = dict(zip(sentences, embeddings))

for sentence, embedding in embeddings_dict.items():
    print(f"Sentence: {sentence}")
    print(f"Embedding: {embedding}")
    print(" ")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md: 0.00B [00:00, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

/Users/nickol/My Fucking Stuff/machine learning/code/local-rag/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

config.json:   0%|          | 0.00/571 [00:00<?, ?B/s]

/Users/nickol/My Fucking Stuff/machine learning/code/local-rag/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

model.safetensors:   0%|          | 0.00/438M [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

Sentence: I would like to play football one day.
Embedding: [-4.21419330e-02  8.62089768e-02 -3.47225778e-02  9.94580239e-03
  6.28689751e-02 -1.68651026e-02 -3.60720754e-02 -1.45378495e-02
  2.88053527e-02  1.04879905e-02  7.16915801e-02 -3.94282751e-02
 -4.30925600e-02  2.41575334e-02  5.15052825e-02  1.35611277e-03
 -2.97665242e-02 -7.42660165e-02 -1.54746436e-02 -4.15016115e-02
 -2.40872335e-02  5.88509403e-02 -8.65249988e-03 -1.57541148e-02
 -4.44777086e-02 -2.39493456e-02  3.70281339e-02 -2.45251395e-02
 -6.23329692e-02  9.17681977e-02 -1.57118437e-03 -4.42774035e-02
  1.71439722e-02 -5.02635874e-02  1.39522149e-06 -4.76675807e-03
 -1.55427819e-02 -6.80074021e-02  2.56581232e-02  6.76748226e-04
  5.12095774e-03 -4.12139669e-02  2.51225824e-03  2.05397932e-03
 -2.02593692e-02  3.90214063e-02  5.24575971e-02 -6.80624023e-02
 -4.66630235e-02  2.69907787e-02 -5.38984127e-03  1.95700992e-02
 -7.44688208e-04 -1.64694656e-02 -2.20816210e-02  3.45719792e-02
 -5.52991070e-02  9.25534591e-03  3.90560250e-03  1.99887622e-02
  2.97616944e-02 -1.61937904e-02  2.21282989e-02  8.19484610e-03
 -4.45170291e-02  3.60123180e-02  6.48730770e-02 -2.11161319e-02
  1.68264657e-02 -4.02416624e-02 -8.01422894e-02 -3.24564055e-02
 -1.51784504e-02  1.36315115e-02  8.48671887e-03 -5.67718446e-02
 -3.45680639e-02  3.84147540e-02  4.22452912e-02  3.01948842e-02
  7.67508638e-04  5.86680276e-03 -9.33883432e-03 -3.05134454e-04
 -2.25898512e-02 -1.56484228e-02  1.33387335e-02  5.02447179e-03
 -3.35684717e-02  3.90539244e-02  1.37878573e-02  1.71710178e-02
  2.72495523e-02 -1.18899010e-02 -5.06900325e-02 -5.97133897e-02
 -2.13040225e-02 -2.07966473e-02  3.52291167e-02 -8.95103533e-03
  8.60783979e-02  1.81850661e-02  5.19030988e-02 -1.66434317e-03
  2.72546913e-02 -1.36349136e-02 -2.49070348e-03 -5.29825576e-02
  1.30034052e-03  1.73523445e-02 -3.21924500e-02 -1.98085308e-02
 -7.53305946e-03  2.52837278e-02 -6.05183430e-02  9.08978190e-03
  4.54791188e-02  1.45130279e-02  6.58202618e-02 -2.16738656e-02
  2.23130290e-03  1.11750877e-02 -2.36956626e-02  1.28126256e-02
  4.55883052e-03 -3.66385840e-02 -1.84371974e-02  5.02403229e-02
 -9.22818109e-03  2.27347631e-02 -5.41081615e-02 -1.93931330e-02
 -1.81230959e-02  6.52926881e-03  6.14726506e-02 -3.12493294e-02
 -4.66159731e-02  4.05594707e-02  2.50204559e-02 -7.04124495e-02
  4.64886948e-02 -1.34241423e-02  2.36781500e-02  2.19857018e-03
 -4.88314815e-02 -3.08583789e-02  4.48233634e-02  4.06534225e-03
 -2.80908681e-02  2.91744387e-03  6.04839772e-02  1.28377844e-02
 -3.39719243e-02 -2.03172397e-02 -1.60600152e-03 -4.15822044e-02
 -1.38559956e-02  2.92508621e-02  2.57417951e-02  5.98105928e-03
 -1.08757615e-02  4.99688499e-02 -4.15925719e-02  4.60915267e-03
 -4.62512150e-02 -4.00051363e-02  3.55435647e-02 -3.43983807e-02
  3.89834233e-02  2.24123690e-02 -1.10052049e-03  3.03760935e-02
 -1.69688426e-02 -6.63055480e-02  2.54206285e-02  4.58742455e-02
  8.86747241e-02 -6.47916719e-02 -1.90311130e-02 -2.45311856e-02
 -3.79075389e-03 -1.31403059e-01 -1.01962909e-02  2.05664858e-02
  4.89468165e-02  2.74564326e-02 -7.58171082e-02  1.31588623e-01
 -3.60405780e-02  3.86811383e-02  3.12357005e-02 -3.78653742e-02
  3.90926674e-02 -7.87086319e-03  7.69422436e-03 -3.53623438e-03
  3.73884849e-02  3.08139455e-02 -5.26470225e-03 -3.14977020e-02
 -2.30518356e-02 -2.79739834e-02 -5.48986793e-02 -4.58995625e-02
  3.09574790e-02 -5.94182163e-02 -9.59703233e-03 -4.27106172e-02
  2.83950847e-03  4.61816266e-02  1.62554476e-02  9.90784355e-03
  7.79508054e-02  6.83203191e-02  8.01656097e-02  2.42517460e-02
  1.44646391e-02 -2.21432913e-02  3.82987894e-02 -2.18906794e-02
 -8.32954794e-03 -1.37089221e-02 -5.72159067e-02  1.65474936e-02
 -6.16524667e-02  3.24447127e-03  6.26614317e-02 -9.18221287e-03
 -5.69592835e-03  3.18101123e-02  2.55981330e-02 -1.23963691e-03
  8.73201992e-03 -1.93610564e-02  2.89366953e-02 -6.61491156e-02
  3.21306884e-02 -1.43167367e-02  1.93230603e-02 -3.36605534e-02
  2.39755996e-02  3.01566906e-02 -1.29236851e-03  3.87982838e-02
 -1.75739974e-02  3.01045962e-02  8.11443478e-02  2.46553235e-02
  2.46757008e-02 -3.17402440e-03 -3.91773358e-02  4.66098487e-02
 -8.00832734e-03  3.85119542e-02 -9.85958353e-02 -5.18575273e-02
 -7.11435303e-02 -1.66051518e-02 -5.67122325e-02 -2.20340118e-02
  4.22776937e-02 -1.51918298e-02  1.57865901e-02  3.53380069e-02
  3.24293636e-02 -1.24607598e-02  1.96199045e-02 -2.40500271e-02
  5.13209589e-02 -3.05608977e-02  2.26722211e-02 -1.01968870e-02
  1.08396905e-02  5.99189254e-04  8.96219630e-03  3.88965569e-02
 -2.34314799e-02 -1.14517575e-02  1.18330186e-02  1.18564442e-02
 -2.24369634e-02  3.13781202e-02 -2.34439578e-02 -8.80183186e-03
  2.50720177e-02  7.24313268e-03  9.12353117e-03  9.38671175e-03
  1.34874871e-02  4.49282527e-02  2.50722412e-02  3.20806503e-02
  3.14896405e-02 -1.41470423e-02  2.16330471e-03  1.04666213e-02
 -2.69777793e-02 -7.95724019e-02 -3.84524986e-02 -5.09586930e-02
  3.89267132e-02 -4.78883348e-02  4.44036648e-02  5.24428040e-02
 -4.11759429e-02 -3.71337794e-02 -6.80950209e-02  2.10611965e-03
  3.72248217e-02  2.13327240e-02 -2.95279026e-02 -3.69942263e-02
 -2.88513061e-02 -3.40474546e-02  1.19224554e-02  5.60424291e-02
  6.70330133e-03  3.49126793e-02  3.01219597e-02 -2.28682775e-02
 -1.39410356e-02  3.49122323e-02  1.71462279e-02 -1.59124024e-02
 -3.63133638e-03  4.79547903e-02 -3.21941860e-02  4.86190096e-02
  4.44580205e-02  3.43003348e-02 -7.67635414e-03 -6.98950514e-03
  8.92967358e-03  5.78463003e-02  9.19487104e-02 -4.92415158e-03
 -8.46205931e-03  1.67848468e-02 -1.34541746e-02 -4.40814253e-03
  2.54270341e-02  8.69095605e-03 -2.71382015e-02  1.58031732e-02
 -3.16457711e-02 -2.47050822e-02  3.63664664e-02  2.90846098e-02
 -7.68190771e-02 -5.40035702e-02  1.94483735e-02  3.71164009e-02
 -4.05943356e-02 -3.68569791e-02 -1.23191234e-02 -1.02560467e-03
  2.45523229e-02  1.04852132e-02 -2.99296714e-02 -2.00039018e-02
  2.94313021e-02  7.21585229e-02  9.34541319e-03  2.40850784e-02
  3.58372199e-04 -3.63786891e-02  2.64338180e-02 -1.33920992e-02
 -5.85773066e-02  1.76492091e-02 -2.83583850e-02  4.25552297e-03
 -7.99594298e-02  7.24114198e-03 -6.87015848e-03  6.74888790e-02
  2.04676874e-02  3.88737507e-02  9.40203294e-02 -3.01998705e-02
  2.89782882e-02  1.23374059e-03 -3.61099318e-02 -7.48260086e-03
  3.66848260e-02 -2.49483231e-02  7.33609051e-02  2.08088551e-02
 -3.04273721e-02 -3.60356383e-02  8.00967868e-03  2.36452837e-02
 -8.90290141e-02  1.62116415e-03 -2.62674559e-02  2.80947797e-02
 -4.47376072e-03  9.37426183e-03 -2.32515018e-02  5.83749078e-03
 -4.43951562e-02 -1.03206737e-02 -4.16434854e-02  2.12684944e-02
 -3.38063166e-02  5.29064015e-02  5.70921320e-03 -4.65948414e-03
  5.33538088e-02 -4.91362847e-02 -4.64726277e-02  4.39739488e-02
  2.79987901e-02  1.54488627e-02  1.79467548e-04 -4.77251448e-02
  6.36211783e-03  3.75950933e-02  7.14505985e-02 -3.77835892e-02
 -7.11722746e-02 -1.44641995e-02  1.05860896e-01  4.98547452e-03
  3.00835762e-02 -1.62414853e-02 -1.25764878e-02 -4.68311980e-02
 -2.11232863e-02 -5.95733225e-02 -7.28488434e-03  2.99955979e-02
 -4.77726012e-03  3.72972456e-03 -5.09113446e-02 -5.96830584e-02
 -2.36135046e-03  3.67252268e-02  1.81782283e-02  8.79488289e-02
  1.68271307e-02 -1.14665348e-02 -3.65120396e-02 -2.90432721e-02
  6.88097477e-02  1.02372169e-02  1.86927188e-02 -3.25279459e-02
  7.74834212e-03  3.06643788e-02 -3.52687761e-02  6.41021207e-02
 -6.08682074e-02  1.23969711e-01 -3.99429258e-03 -1.69194490e-02
  3.68161500e-02  2.78695778e-04  1.91712976e-02 -1.95754580e-02
  4.85432521e-02  1.17831014e-03 -5.80559252e-03  9.77217499e-03
  1.17808776e-02 -2.92156637e-02  3.52486297e-02 -2.82441154e-02
  1.95365455e-02 -1.68790948e-02 -6.26057237e-02  1.77426506e-02
 -1.30827678e-02 -1.04585011e-02  1.57510806e-02  3.19623179e-03
  6.46778429e-03  7.66027533e-03  2.93293525e-03 -2.80985888e-02
  4.58604470e-02  8.17527473e-02 -5.38764372e-02  9.30268690e-03
 -1.76553093e-02  1.17175495e-02 -1.12980353e-02  2.32765097e-02
 -2.48518470e-03  1.71643570e-02  5.56602366e-02 -5.70257567e-02
  2.89177010e-03 -6.43639266e-02  1.67319849e-02  1.23970425e-02
 -2.50536166e-02  9.36676655e-03  1.67093601e-03 -2.44847741e-02
 -1.74353214e-03 -2.73183212e-02 -8.84438865e-03  6.47475664e-03
  7.38338148e-03 -5.92756122e-02  4.32955995e-02 -5.66085391e-02
 -4.65399772e-02  1.40798343e-02  7.35751260e-03 -3.73779461e-02
  7.99655616e-02  2.32184790e-02 -7.80113554e-03  2.89302729e-02
  1.10732364e-02 -3.76829482e-03  8.02278332e-03 -3.20234671e-02
  3.16703729e-02  4.07953151e-02  2.11991109e-02  2.94805001e-02
 -6.40522540e-02  7.58093875e-03 -1.52288796e-02 -2.26057060e-02
 -3.42460386e-02 -1.85487475e-02 -2.97277682e-02 -6.63049472e-03
 -1.48118399e-02 -2.03677397e-02 -4.63865325e-02 -9.19946004e-03
  1.15747973e-02  1.93687230e-02 -6.12100251e-02  9.18578953e-02
  9.17172339e-03  3.81999463e-02  1.23087997e-02  3.88271064e-02
 -2.85930969e-02 -4.39263247e-02  5.31633664e-03  3.60816680e-02
 -1.79058388e-02 -3.47049115e-03 -1.98410973e-02 -4.36820276e-02
  3.97946127e-03 -9.84962098e-03 -2.04777401e-02 -4.66857500e-33
  2.36037150e-02  4.27165776e-02  1.60175338e-02  9.07496549e-03
 -3.31564881e-02 -3.11950557e-02  4.39406522e-02 -5.42510999e-03
  3.87352780e-02 -5.20811358e-04  1.16346637e-02 -1.91048644e-02
 -6.27174135e-03  9.60074645e-03  4.82298136e-02  4.93105315e-03
  7.13488413e-03 -3.46103981e-02  2.25282777e-02  3.61669972e-03
 -6.65510595e-02 -3.69009264e-02 -1.45271672e-02  5.65894172e-02
 -7.05907180e-04 -3.70065905e-02 -5.23054339e-02  5.44012710e-03
 -9.39886272e-03  2.55560428e-02 -9.98736266e-03 -6.36610836e-02
  1.34070031e-02 -5.01966886e-02  1.02917440e-02  7.04028085e-02
  2.57614795e-02  7.18973204e-02 -5.96545562e-02 -3.13221775e-02
 -3.42258438e-02 -6.17544875e-02  2.24985965e-02 -4.21341173e-02
 -7.38418056e-03 -3.58253792e-02  1.87841877e-02  2.34513097e-02
  9.70450640e-02 -5.18463552e-02 -5.04333749e-02 -2.05970444e-02
 -1.15538214e-03 -9.89495497e-03 -1.39329508e-02  1.53904548e-02
  1.73478033e-02  5.92978671e-03  2.76185647e-02 -8.35456140e-03
  4.45363745e-02  2.51996238e-02 -1.96068659e-02  3.46202217e-02
  1.30967367e-02  3.57388370e-02  2.32412294e-03 -6.56854883e-02
 -6.12615608e-03 -4.15793285e-02 -1.16251372e-02 -2.33268626e-02
 -1.05544152e-02  1.29014831e-02  6.02750061e-03  1.67463208e-03
 -6.46305010e-02 -4.00837287e-02  3.33339758e-02  2.86932220e-03
 -1.07474141e-02 -3.32924508e-04  3.66931111e-02  3.49661931e-02
 -1.36843072e-02  1.29645355e-02  3.44866961e-02  2.11876892e-02
  1.35586979e-02  3.16101708e-03 -1.26141254e-02 -5.79031184e-02
 -1.04587907e-02  4.55750190e-02  4.11305167e-02  1.93561725e-02
 -2.09623557e-02  2.42736880e-02 -3.54885943e-02  1.11134537e-02
 -4.33827564e-02 -2.79934146e-02 -3.10020037e-02 -1.00173682e-01
 -2.08775438e-02  3.32189240e-02 -2.54675020e-02 -1.17323864e-02
 -2.54455693e-02  6.26930594e-03 -5.52676357e-02  3.84763218e-02
  1.00748045e-02 -4.14781049e-02  5.26465140e-02 -1.75452586e-02
 -1.39506096e-02 -2.10702373e-03 -9.02464911e-02 -5.04407063e-02
  1.43574402e-02  5.48414476e-02 -3.57655920e-02  3.54524292e-02
 -6.80708326e-03 -2.77096257e-02  2.56744418e-02  1.48891741e-02
 -4.42592762e-02 -5.49812848e-03 -3.62563459e-03  3.73357274e-02
  2.00421596e-07 -5.63628748e-02 -2.47853976e-02 -1.36601767e-02
  5.03540486e-02  1.63597669e-02  3.16408984e-02  8.95711780e-03
  6.53292611e-02  4.31989599e-03  6.85982853e-02  1.10616982e-02
  6.39954209e-02 -3.03397304e-03  2.73473542e-02 -3.40118352e-03
 -1.01559302e-02  5.88082597e-02  3.30236778e-02  5.76714985e-03
 -6.80842623e-02 -4.99267969e-03  3.87153588e-02  4.69814837e-02
  3.18175480e-02  1.07288035e-02  2.70126220e-02 -3.53535190e-02
 -3.82524654e-02  7.60040618e-03 -1.45361135e-02 -1.06046675e-02
 -2.66077016e-02 -1.75915472e-02  1.26938242e-02 -1.36122489e-02
 -5.09654991e-02  2.66877189e-03  5.46239279e-02 -1.79517996e-02
  5.50872386e-02 -8.37334257e-04  2.58302893e-02 -1.82946771e-02
  3.35641205e-02  4.64599812e-03 -4.63530533e-02  2.85135917e-02
 -2.65800096e-02 -5.08020148e-02  1.48169966e-02 -4.50407192e-02
  1.00877192e-02 -2.30924562e-02 -4.89265583e-02  3.37110721e-02
  1.32500790e-02 -2.42823884e-02  2.83877365e-02  3.38864587e-02
  2.28094850e-02 -4.16291729e-02  1.28687881e-02  2.22597067e-04
  6.30887076e-02 -5.98659776e-02 -4.19441536e-02  1.85671430e-02
  9.78431677e-35  2.12644134e-02  3.74942906e-02  5.40988743e-02
 -4.50720415e-02  1.63582596e-03 -5.53072477e-03  5.05663380e-02
 -7.34593393e-03  1.74319725e-02  3.58707160e-02 -1.73147507e-02]

Sentence: My favourite player is Lionel Messi.
Embedding: [-9.90247503e-02 -1.90540985e-03 -2.33962387e-02  6.37389049e-02
  6.43784553e-02 -4.07886468e-02 -5.89959212e-02 -2.80452445e-02
  2.19779704e-02  2.29807906e-02  2.27306150e-02  7.32094795e-02
 -6.50582463e-03 -6.70225397e-02  6.46591093e-03 -2.27945931e-02
 -2.82945484e-03  3.33998539e-03  2.67212652e-02 -1.16862813e-02
 -2.92199035e-03  3.87871750e-02  2.90335789e-02 -3.28379357e-03
  2.36213412e-02  6.20915880e-03  4.09477623e-03 -5.60967363e-02
 -1.31482594e-02  4.32757325e-02 -7.69102722e-02 -2.61121746e-02
 -1.89659297e-02 -1.68139802e-03  1.41411556e-06 -4.85226773e-02
 -1.15754339e-03 -2.86258403e-02  3.72520462e-02 -6.25448376e-02
  3.03913206e-02  1.46675557e-02 -1.60546470e-02 -2.90867779e-02
 -2.03213491e-03  5.06768450e-02  4.64342209e-03 -1.09207502e-03
 -3.43221836e-02 -4.70851921e-02 -1.15825348e-02 -8.63194913e-02
  3.50082330e-02  2.68852785e-02 -3.96693610e-02 -5.42081594e-02
  2.86159031e-02  2.66264752e-03 -2.08659545e-02  2.42019091e-02
 -3.97277158e-03 -6.76978230e-02  1.94154829e-02 -1.72367040e-02
  5.22235967e-02 -3.24257724e-02  1.78447645e-02  2.35172622e-02
  2.63940766e-02  4.50426247e-03 -1.65820457e-02 -3.55572850e-02
  3.59518863e-02 -6.63191825e-03  1.19105848e-02  1.17543833e-02
  1.73186716e-02 -5.41994628e-03 -2.05814559e-03  1.81420380e-03
  5.77176586e-02  4.10342123e-03  4.06289995e-02 -2.82083154e-02
 -4.12900075e-02 -1.40235359e-02 -2.38019414e-03 -2.47721393e-02
  8.76818150e-02  6.25252724e-02 -5.19133778e-03 -4.15889546e-02
  1.53800156e-02  1.78303607e-02 -6.26845285e-02 -3.07077095e-02
 -8.22812319e-03 -4.23524007e-02 -2.51299627e-02 -2.75774729e-02
  2.90938765e-02  3.44342068e-02  5.77357858e-02  3.29496637e-02
 -2.83701438e-02  2.98107397e-02 -1.17630390e-02 -2.08152551e-02
  4.78041954e-02 -3.07343267e-02 -4.09895964e-02 -3.93965282e-02
  3.78067680e-02  7.02678710e-02 -1.76773034e-02  1.75333284e-02
  3.65026258e-02  4.94872294e-02 -3.50648873e-02 -4.10312116e-02
  4.51270826e-02  2.33147200e-03 -1.77302714e-02  6.34042695e-02
 -3.04791778e-02 -1.71727687e-02 -1.04588397e-01  1.20610436e-02
 -2.14199740e-02 -1.78203303e-02 -3.00592855e-02 -3.69892945e-03
 -7.75757665e-03  4.41164477e-03  3.71686742e-02 -7.23332837e-02
 -2.43275054e-02 -4.77611460e-02  4.16168310e-02 -4.55801822e-02
  4.53373082e-02 -4.69533876e-02  1.47721386e-02  1.13002378e-02
  2.72611044e-02 -1.50657194e-02 -1.41830067e-03 -2.50256211e-02
  2.67860363e-03  5.79929836e-02  3.55481356e-02 -5.71882818e-03
 -5.13423085e-02 -2.13949196e-02 -4.80133258e-02 -3.38920727e-02
  3.00781112e-02 -1.38358464e-02  1.07800467e-02  1.16270389e-02
 -7.46993646e-02  2.26932801e-02 -4.50668931e-02 -2.19941419e-02
 -3.26411091e-02 -7.23945871e-02  7.13917008e-03 -1.87467004e-03
 -8.67737085e-03  2.32539102e-02  2.10816264e-02 -1.85188130e-02
 -2.73994282e-02 -5.43670356e-02 -9.81959514e-03 -2.47058421e-02
  2.31043119e-02  4.45837937e-02 -1.27420677e-02 -2.07887441e-02
  1.21860523e-02 -3.05465590e-02  6.19216301e-02  9.89975482e-02
  5.27836531e-02 -3.19507085e-02 -6.87651858e-02  6.81642890e-02
 -4.49389638e-03  2.30999291e-02  3.46876085e-02  6.40763668e-03
 -3.81859317e-02  1.08532943e-02  6.81979535e-03 -1.17014097e-02
  1.50707550e-02 -5.36611816e-03  9.15822107e-03 -2.35722847e-02
  3.65260267e-03  8.99850857e-03 -2.68692076e-02 -1.24947885e-02
 -1.89629477e-02 -6.92451233e-03 -3.42151001e-02  1.56132574e-03
 -1.72973108e-02 -2.00491622e-02 -6.76893890e-02 -7.44635053e-03
  2.45731324e-02 -5.74120581e-02  2.12356951e-02  2.23030914e-02
 -1.33659961e-02  5.23985140e-02  1.58134438e-02  3.99443135e-02
 -4.10341881e-02  1.33738071e-02  1.73782948e-02  2.20900513e-02
 -1.27683301e-02 -5.48269562e-02  6.93615526e-02  4.13072817e-02
  4.44390066e-03  3.21403891e-02 -1.21581471e-02 -5.33389188e-02
  8.41346458e-02  3.96201983e-02  2.14135069e-02  1.88282691e-02
  1.21477190e-02 -2.47558728e-02  2.78339535e-02 -1.80895887e-02
 -2.99622351e-03  8.41203779e-02  7.15365857e-02 -5.59678413e-02
 -2.27549998e-03 -2.63921972e-02  6.82960302e-02 -2.04268890e-03
  1.28999064e-02 -2.32357793e-02  4.00112942e-02 -2.56285463e-02
 -5.04563823e-02  1.79435518e-02 -1.65447034e-02 -3.87094766e-02
 -2.11651511e-02 -1.94386858e-02 -2.20223051e-02 -1.76626705e-02
  3.50694545e-02  3.94111872e-02 -2.65153348e-02  2.36442368e-02
  4.96560186e-02  1.34034781e-02 -2.81160474e-02 -9.44614783e-03
  7.02969451e-03 -8.83465167e-03 -2.68133543e-02 -6.58565387e-02
  1.01716612e-02  7.36133531e-02 -7.21201184e-04  1.46029023e-02
 -4.63616010e-03  6.03477564e-03 -4.12768982e-02  2.25110315e-02
  5.92978019e-03  3.35839088e-03  7.77312880e-03  4.22213078e-02
  6.18624641e-03  2.44178642e-02  3.80354077e-02 -2.27284133e-02
  8.49364698e-03 -5.68406051e-03 -3.82256955e-02  4.69671469e-03
  2.77426504e-02  3.01919766e-02  7.91132823e-03  1.90184601e-02
 -3.88358831e-02 -1.40137095e-02 -4.01429161e-02 -2.09691841e-02
  3.71512063e-02 -5.03521152e-02  3.23290639e-02  1.82448868e-02
  6.08984288e-03 -7.49565586e-02 -2.77682822e-02  3.38129997e-02
  4.61190008e-02 -2.23466399e-04 -5.93072027e-02 -3.15524861e-02
 -8.64315499e-03 -2.50985045e-02  7.66312778e-02  2.19847709e-02
  1.96973328e-02  4.40087728e-02  9.97922663e-03 -4.80214283e-02
  8.28247797e-03  2.63770558e-02  5.84557354e-02  1.46468012e-02
  2.65163463e-02 -2.63707392e-04 -2.20873971e-02  4.96048890e-02
 -1.89147480e-02 -7.37223541e-03  2.64883302e-02  3.66881453e-02
  7.98859820e-02  2.16418114e-02  1.99426375e-02 -1.79915447e-02
  5.35454862e-02 -2.21861526e-02 -3.57713774e-02 -3.95694636e-02
  4.68982942e-03 -5.96044995e-02  7.59065803e-03 -5.02028503e-02
  2.37660799e-02 -1.46299768e-02  4.03284431e-02 -1.87344607e-02
 -6.91441149e-02 -7.70239532e-02  1.60426609e-02 -1.08855322e-01
  6.42079394e-04 -5.11044078e-02 -1.02049001e-02 -7.33151287e-02
 -3.35940085e-02 -4.53894353e-03 -1.07758474e-02 -4.93255444e-02
  9.86506511e-03  4.37674783e-02 -8.07399116e-03  2.49483213e-02
 -4.37270068e-02  5.13645867e-03  8.44898075e-03  4.94752303e-02
  5.08498633e-03  4.08227630e-02  2.14904509e-02 -2.35439260e-02
  4.00152504e-02 -1.58931930e-02 -1.14622004e-02  1.45257022e-02
  1.06642535e-02 -2.89044697e-02  2.81080157e-02  3.04801222e-02
  3.54593657e-02  2.08901595e-02 -2.59740255e-03  6.95286617e-02
 -1.74370445e-02  2.01507322e-02  6.50980975e-03 -2.29827985e-02
  3.69076338e-03  1.45088574e-02  3.65724764e-03 -3.61877456e-02
 -1.11252405e-02 -5.14559597e-02 -1.47781782e-02  9.70016606e-03
  1.11296652e-02  3.18332426e-02  2.87443530e-02 -1.32882344e-02
  4.16213311e-02  4.15933020e-02  3.60265486e-02  3.60284233e-03
 -3.20709241e-03 -3.34476642e-02 -2.90504824e-02  3.02239228e-02
  6.13380559e-02 -1.33333616e-02 -9.65852439e-02  5.87089546e-02
  2.95660645e-02 -2.57316437e-02 -5.35768494e-02 -3.22511308e-02
 -5.26687736e-03 -4.29155268e-02  4.59833108e-02 -3.22144628e-02
 -1.25457607e-02  4.48699519e-02  5.68024069e-02  6.67991042e-02
  2.27595977e-02 -5.61241712e-03 -2.27808859e-02  7.84830377e-03
 -5.59879765e-02 -1.03610158e-02  3.49822827e-02 -1.41525827e-02
  4.77391714e-03 -7.50541454e-03  2.91303769e-02 -8.34433660e-02
 -1.86997056e-02  8.02820548e-03 -8.12767893e-02  3.73652317e-02
 -5.93682788e-02 -3.75216041e-04 -2.65931245e-02 -1.60061810e-02
  5.84423766e-02  1.71361156e-02 -6.99431077e-02  5.81129789e-02
  5.31323720e-04  5.30951433e-02 -9.96262766e-03 -3.67618422e-03

In [34]:
embeddings.shape

(3, 768)

In [39]:
%%time 

for item in tqdm(pages_and_chunks_over_min_token_len):
    item["embedding"] = embedding_model.encode(item["sentence_chunk"])

  0%|          | 0/1680 [00:00<?, ?it/s]

CPU times: user 47.8 s, sys: 10.4 s, total: 58.3 s
Wall time: 1min 20s

In [40]:
text_chunks = [item["sentence_chunk"] for item in pages_and_chunks_over_min_token_len]

len(text_chunks)

1680

In [41]:
random.sample(text_chunks, k=1)

['Another is that combining low- and high-GI foods changes the GI for the meal. Also, some nutrient-dense foods have higher GIs than less nutritious food. (For instance, oatmeal has a higher GI than chocolate because the fat content of chocolate is higher.)Lastly, meats and fats do not have a GI since they do not contain carbohydrates. 250 | Digestion and Absorption of Carbohydrates']

In [43]:
%%time

text_chunk_embeddings = embedding_model.encode(
    text_chunks,
    batch_size=64,
    convert_to_tensor=True
)

text_chunk_embeddings.shape

CPU times: user 2.46 s, sys: 3 s, total: 5.46 s
Wall time: 37.7 s

torch.Size([1680, 768])

In [44]:
text_chunks_and_embeddings_df = pd.DataFrame(pages_and_chunks_over_min_token_len)
embeddings_df_save_path = "text_chunks_and_embeddings_df.csv"
text_chunks_and_embeddings_df.to_csv(embeddings_df_save_path, index=False)

In [45]:
text_chunks_and_embeddings_df_load = pd.read_csv(embeddings_df_save_path)
text_chunks_and_embeddings_df_load.head()

,page_number,sentence_chunk,chunk_char_count,chunk_word_count,chunk_token_count,embedding
0,-39,Human Nutrition: 2020 Edition UNIVERSITY OF HA...,308,42,77.00,[ 6.74242303e-02 9.02281702e-02 -5.09549305e-...
1,-38,Human Nutrition: 2020 Edition by University of...,210,30,52.50,[ 5.52156046e-02 5.92139922e-02 -1.66167002e-...
2,-37,Contents Preface University of Hawai‘i at Māno...,766,116,191.50,[ 2.79801544e-02 3.39813754e-02 -2.06426661e-...
3,-36,Lifestyles and Nutrition University of Hawai‘i...,941,144,235.25,[ 6.82566613e-02 3.81275080e-02 -8.46853200e-...
4,-35,The Cardiovascular System University of Hawai‘...,998,152,249.50,[ 3.30264308e-02 -8.49766564e-03 9.57161095e-...

In [47]:
text_chunks_and_embeddings_df_load["embedding"]

0       [ 6.74242303e-02  9.02281702e-02 -5.09549305e-...
1       [ 5.52156046e-02  5.92139922e-02 -1.66167002e-...
2       [ 2.79801544e-02  3.39813754e-02 -2.06426661e-...
3       [ 6.82566613e-02  3.81275080e-02 -8.46853200e-...
4       [ 3.30264308e-02 -8.49766564e-03  9.57161095e-...
                              ...
1675    [ 1.85622703e-02 -1.64277274e-02 -1.27045512e-...
1676    [ 3.34721096e-02 -5.70440777e-02  1.51489452e-...
1677    [ 7.70515651e-02  9.78556927e-03 -1.21817468e-...
1678    [ 1.03045136e-01 -1.64702386e-02  8.26848485e-...
1679    [ 8.63773674e-02 -1.25358859e-02 -1.12746637e-...
Name: embedding, Length: 1680, dtype: object

In [49]:
str_emb = text_chunks_and_embeddings_df_load["embedding"][0]

str_emb

'[ 6.74242303e-02  9.02281702e-02 -5.09549305e-03 -3.17545645e-02\n  7.39082247e-02  3.51976342e-02 -1.97986476e-02  4.67692316e-02\n  5.35727292e-02  5.01227845e-03  3.33928838e-02 -1.62215461e-03\n  1.76080819e-02  3.62652913e-02 -3.16662947e-04 -1.07117947e-02\n  1.54257547e-02  2.62176339e-02  2.77662324e-03  3.64942662e-02\n -4.44109626e-02  1.89362112e-02  4.90118116e-02  1.64020602e-02\n -4.85782735e-02  3.18290503e-03  2.72992756e-02 -2.04757787e-03\n -1.22828595e-02 -7.28049502e-02  1.20446039e-02  1.07300067e-02\n  2.10001529e-03 -8.17773119e-02  2.67830183e-06 -1.81427989e-02\n -1.20802736e-02  2.47174520e-02 -6.27467185e-02  7.35438466e-02\n  2.21624505e-02 -3.28767709e-02 -1.80095714e-02  2.22952366e-02\n  5.61365113e-02  1.79513043e-03  5.25931865e-02 -3.31747695e-03\n -8.33875965e-03 -1.06284656e-02  2.31917971e-03 -2.23934688e-02\n -1.53012108e-02 -9.93055850e-03  4.65322286e-02  3.57469432e-02\n -2.54760254e-02  2.63694208e-02  3.74908559e-03 -3.82680483e-02\n  2.58325282e-02  4.12872806e-02  2.58181412e-02  3.32973078e-02\n -2.51783598e-02  4.51521464e-02  4.49088111e-04 -9.96620432e-02\n  4.99491058e-02  7.13512599e-02  6.96959272e-02  3.85235436e-02\n  9.95332841e-03  4.18640487e-02 -3.22836600e-02 -4.39972244e-03\n  5.05052656e-02 -5.52355759e-02 -2.80108638e-02 -2.27898005e-02\n -1.71496421e-02  1.87901538e-02  1.56440977e-02 -1.39884546e-03\n -6.59480970e-03  3.02389562e-02  6.37047598e-03  1.96740404e-02\n -4.15964704e-03 -3.64310890e-02 -1.58165582e-02  2.32676435e-02\n  2.68640055e-04  2.17785724e-02  6.89126877e-03 -2.32419111e-02\n  7.25939795e-02 -5.01198173e-02  8.08757693e-02 -2.48893499e-02\n  2.90674791e-02  5.52490167e-02 -9.34375599e-02 -1.32117337e-02\n  1.59285672e-03  1.37981642e-02  2.15566717e-02 -3.27911749e-02\n -2.90928539e-02  5.62359244e-02 -3.36900190e-03  8.68975837e-03\n  6.06928952e-04 -1.29652508e-02 -1.35400677e-02  1.28430333e-02\n -1.04978811e-02 -4.55567911e-02 -3.67391445e-02 -7.17338175e-02\n  2.54513342e-02  5.39568849e-02 -2.06747781e-02  4.84254844e-02\n -5.90827167e-02  1.02891870e-01  2.26163194e-02  1.03315832e-02\n  1.44357951e-02 -4.90253493e-02 -9.47684050e-03 -2.19099224e-02\n -2.80026142e-02  4.23527695e-03 -1.54677290e-03  1.05041815e-02\n -6.69239368e-03  1.90845504e-02  1.41930496e-02 -5.20690605e-02\n -6.22595139e-02 -2.99086310e-02 -6.42764568e-02 -2.39539705e-02\n  7.14202598e-02 -1.83041878e-02  8.09936747e-02 -1.79562513e-02\n  3.72843705e-02  7.35376328e-02 -2.37267627e-03 -4.52059880e-02\n  4.93059754e-02  6.30556121e-02  9.36354175e-02  8.67178757e-03\n  1.12302259e-04 -3.48906517e-02  4.02741320e-02  5.24062812e-02\n  8.55109747e-03 -1.11350244e-04 -8.96978676e-02 -1.52497683e-02\n -7.32253958e-03  3.45981643e-02  1.02752959e-02 -1.70997679e-02\n  1.46063678e-02  4.21932004e-02 -5.60591929e-02  3.15297768e-03\n -1.93180796e-02 -1.37818120e-02  5.04867770e-02  3.05518992e-02\n -4.77813184e-02  6.20951643e-03  4.16892841e-02 -1.75102111e-02\n  4.40745912e-02 -7.41178840e-02  1.78745873e-02  2.80853041e-04\n -5.29327802e-02 -8.40260088e-03 -3.77157144e-03 -1.99795086e-02\n  4.42504659e-02 -4.04359922e-02  3.70720848e-02  2.28037927e-04\n -2.61265673e-02 -8.13645944e-02  7.35088615e-05  3.39099811e-03\n  8.93966388e-03 -1.79453529e-02  2.71475632e-02 -7.76860192e-02\n  5.10037094e-02  2.96539497e-02  2.64490042e-02 -7.93659419e-04\n -3.21819074e-02  3.80366221e-02  2.37715300e-02 -1.31111825e-02\n  2.00448092e-02 -2.07266561e-03 -5.85778579e-02 -1.51491854e-02\n  4.73964736e-02  9.37170722e-03 -2.27221586e-02 -3.49049852e-03\n -1.11097069e-02 -1.73014589e-02  1.91120859e-02  7.33278245e-02\n  2.52724867e-02  2.29908042e-02 -8.63382965e-02 -2.05237642e-02\n -2.40728613e-02  7.85169844e-03  5.92232570e-02 -1.95050165e-02\n  7.27934530e-04  4.86338772e-02  3.90096009e-02  5.45958988e-02\n -3.78994755e-02  2.14201622e-02  2.44414667e-03  4.14731763e-02\n  7.67865777e-02  3.91553007e-02 -2.11405847e-02  4.84219529e-02\n -5.93219958e-02  2.98017520e-03 -3.89345512e-02 -3.50046461e-03\n -6.14648871e-02  2.82716919e-02 -3.57951298e-02 -2.45329775e-02\n -6.73675239e-02  9.39845145e-02  2.53813528e-02 -8.76086205e-03\n  9.62462183e-03  1.65698957e-02 -5.34133501e-02 -1.83703005e-02\n -5.44540286e-02 -5.18859811e-02 -3.99824083e-02  6.01737648e-02\n -4.02110331e-02  3.40260677e-02  7.12319510e-03 -1.76352486e-02\n  2.63533667e-02 -8.16680342e-02  4.15973030e-02  1.10543594e-02\n  7.73297669e-03 -3.55056673e-02 -5.87681588e-03 -1.41534479e-02\n -2.71463636e-02  2.38195769e-02 -3.44787771e-03  3.28347944e-02\n  4.43370547e-03 -3.00127808e-02  4.79745306e-02 -4.05801013e-02\n -2.13998370e-02  7.87418708e-02 -1.56304650e-02  1.89303067e-02\n  2.67554782e-02 -4.17765640e-02  6.49793260e-03  1.60408067e-03\n  6.68079853e-02 -5.28950803e-02  4.18435931e-02 -5.38789518e-02\n  2.94470470e-02  1.48594240e-02 -4.29649390e-02  3.44470292e-02\n -2.75051333e-02  1.37509359e-02  4.09903675e-02 -8.88956897e-03\n -3.05098691e-03  3.34398262e-02 -4.04661288e-03  3.28654051e-02\n -1.46095185e-02  2.07155384e-02 -3.05071287e-03 -3.89432386e-02\n  4.88118920e-03 -2.98723225e-02  1.74396450e-03  8.60807076e-02\n  6.68614404e-03 -1.62573718e-02 -8.12874641e-03 -3.57048810e-02\n -4.79689948e-02  2.25290712e-02  2.27440670e-02 -1.93761988e-03\n  1.19013004e-02 -1.03209540e-02 -1.32569689e-02 -1.44635225e-02\n -3.17995809e-03 -2.89135128e-02  4.88829706e-03  4.54248637e-02\n -1.08878419e-01 -4.45946380e-02 -1.69045979e-03  1.78573783e-02\n  5.74182831e-02 -1.36333192e-02  2.30217595e-02 -4.61972505e-02\n -3.12755220e-02  6.21251715e-03 -4.99114506e-02 -3.68294045e-02\n -3.47710438e-02  2.01239600e-03  3.99565703e-04  6.69961870e-02\n -1.72363892e-02 -5.30299619e-02  9.97220911e-03  2.38085296e-02\n -1.78703535e-02  1.95265561e-02 -5.12357764e-02 -3.79956029e-02\n  2.52402592e-02 -3.15280147e-02  2.82167550e-02 -1.40533466e-02\n  2.75645517e-02 -7.57218618e-03 -3.13508101e-02 -1.07884558e-03\n  3.08622047e-02  8.46480727e-02 -2.32757386e-02 -6.32615834e-02\n  6.48503602e-02  5.11871055e-02 -4.69511282e-03  2.16896739e-02\n  2.28435379e-02 -1.75960083e-02 -1.76536355e-06  5.03176525e-02\n -1.49554238e-02  1.59846917e-02  2.32572109e-03 -5.87268211e-02\n  3.70019227e-02  7.27753043e-02 -3.38272154e-02 -1.87539011e-02\n  4.67500798e-02 -1.55598512e-02  3.56517769e-02  9.99829452e-03\n -2.03129463e-02 -5.68483733e-02 -4.97143790e-02 -2.92548966e-02\n  2.40868051e-02 -4.68073227e-02  1.05818305e-02  4.22137370e-03\n -8.80386494e-03 -2.48464057e-03  7.10905809e-03 -4.04599402e-03\n  1.78003218e-02 -2.39113551e-02 -6.87355548e-03  3.71275879e-02\n -1.40690738e-02 -1.23914592e-02  3.34878154e-02  3.99022363e-02\n -1.66716184e-02  1.48813054e-02  3.49213332e-02  4.19481806e-02\n  4.10648249e-02  2.83284485e-02  3.04326639e-02 -2.09015291e-02\n  2.80192606e-02 -5.12436293e-02  2.03535538e-02 -1.46296564e-02\n -9.95220151e-03 -2.10910197e-02  4.48565595e-02 -3.29360366e-02\n -4.55907695e-02  4.41765971e-02 -2.76714470e-03  5.73454089e-02\n -4.17592842e-03 -2.92153358e-02  2.77037285e-02 -1.52596897e-02\n -6.19948208e-02  2.93321908e-02  4.48227338e-02  2.11812127e-02\n -9.11899004e-03 -3.65736266e-03 -3.88816521e-02  1.71847213e-02\n  7.24660978e-02 -5.53688258e-02 -4.00997885e-02 -1.95436087e-02\n -1.30693186e-02  1.26573974e-02  4.20498289e-03 -3.15169245e-02\n  9.33311321e-03  7.58654159e-03  1.25840707e-02  3.94737981e-02\n  9.20807421e-02  3.61451022e-02  2.13236008e-02  9.98289883e-03\n -2.49774624e-02  4.99336496e-02  3.23858969e-02 -8.34817591e-04\n  4.27204110e-02 -5.24610057e-02  1.93347149e-02 -2.21239924e-02\n  4.54791710e-02 -1.27856201e-02 -1.74304023e-02  2.59035584e-02\n -2.30377279e-02 -3.11631598e-02  1.57731678e-02  2.08224822e-03\n -3.28662805e-02 -2.62360685e-02 -4.70342860e-02  5.60605116e-02\n  5.20098675e-03  1.29133379e-02  1.79670993e-02 -1.74150057e-02\n -5.59645407e-02 -1.73937846e-02 -2.74459012e-02  3.91347595e-02\n -4.81797243e-03  2.67288927e-03 -8.50864220e-03 -4.77053337e-02\n  5.87333320e-03  7.48375431e-03 -3.30419354e-02 -2.74910405e-02\n -8.25846009e-03 -4.79961820e-02  1.53875239e-02  4.05623019e-02\n -1.79937277e-02 -1.53878834e-02 -5.41522214e-03  3.67399752e-02\n -3.17350440e-02 -9.00536962e-03 -1.22322142e-02  2.12535057e-02\n  1.19459182e-02 -8.74406192e-03  1.68865100e-02 -1.45980315e-02\n -3.32913958e-02  3.64130251e-02 -5.11904955e-02  7.46199023e-03\n -3.65407728e-02 -4.26876880e-02 -2.81809084e-02 -1.34026548e-02\n  2.66018566e-02  2.10149381e-02 -1.68677662e-02 -6.13206737e-02\n -2.10965145e-03 -2.48019695e-02  2.22637914e-02  9.25851241e-03\n -5.53785544e-03 -5.55743836e-02  7.05644209e-03 -2.49683131e-02\n -2.00949833e-02  6.42916840e-03  1.39889428e-02 -1.45896850e-02\n -4.80521061e-02  8.32006633e-02  5.49593121e-02  2.75904033e-02\n -4.87239053e-03  4.76308390e-02  2.18205489e-02 -7.30828196e-03\n -2.96602864e-02  3.70682217e-03 -6.46586269e-02 -2.82096323e-02\n  7.46354694e-03 -8.55471268e-02  1.27533143e-02  2.84523796e-03\n  1.85691677e-02  5.43100946e-02 -1.22985572e-01 -7.54426047e-02\n  2.15049163e-02 -1.20498702e-01  3.25353257e-03 -6.59889658e-04\n  1.99478306e-03 -9.97205637e-03  5.75397052e-02 -6.96372551e-33\n  3.85706723e-02 -4.36092988e-02  2.15196759e-02  1.85362808e-02\n  4.17567044e-02  2.03666389e-02 -1.15470262e-02 -2.76781097e-02\n -1.84317399e-02  8.46618786e-03 -8.76250560e-04  8.28469812e-04\n  2.27911212e-02 -3.13029811e-02  2.50838716e-02 -8.73164274e-03\n -4.67526447e-03 -2.55096927e-02  5.05392859e-03 -3.37545425e-02\n -4.94915545e-02  1.56323891e-02 -6.80953031e-03  2.48010866e-02\n  3.05012055e-02  2.15578768e-02  2.22171377e-02 -1.81512497e-02\n -5.80374040e-02 -1.70573331e-02  1.63371060e-02  2.18999535e-02\n  2.73491833e-02  3.90386991e-02 -2.33403835e-02 -6.28673062e-02\n  2.03809701e-02 -3.03173754e-02 -3.23167257e-02 -7.20663592e-02\n -3.86938378e-02 -9.82737727e-03  2.51085777e-02  3.67949679e-02\n -1.72969457e-02  3.02671231e-02 -1.57558993e-02 -3.97941209e-02\n  2.30327770e-02  3.11237890e-02 -1.92873012e-02  1.18442606e-02\n -4.82675619e-03  4.07815166e-02  1.03846833e-03  1.04635991e-01\n  1.90627854e-02  8.35709367e-03  2.53371056e-03 -3.13189765e-03\n -2.78254058e-02  1.84029397e-02  2.07019020e-02  3.69079113e-02\n  2.74160434e-03 -6.01582080e-02  2.97910068e-02  1.89672392e-02\n -3.44730914e-02  1.51036624e-02 -3.64224464e-02 -2.45670527e-02\n  1.18608791e-02  1.51273813e-02 -2.76326332e-02 -8.74801502e-02\n -1.20377848e-02  8.14919546e-02  1.35023976e-04 -7.99897965e-03\n -8.29238296e-02 -1.49161601e-03  2.35584099e-02  7.71071017e-03\n -4.45612222e-02  5.73876547e-03 -1.62402578e-02  7.59660592e-03\n  2.89723580e-03  3.01373890e-03 -1.80747472e-02 -1.61253046e-02\n  7.45354267e-03  3.02701797e-02  5.38823903e-02 -8.83090217e-03\n  4.13308106e-02 -4.52555344e-02  2.63358876e-02 -2.33413596e-02\n -5.72936907e-02  3.07124294e-02  3.20133977e-02 -2.22796127e-02\n  2.18933504e-02 -8.84479210e-02 -1.64413434e-02 -1.85784381e-02\n  3.18324044e-02 -5.17816097e-02  1.16167264e-02 -4.08341503e-03\n  4.00550738e-02 -2.35409085e-02 -4.24223319e-02  1.25499824e-02\n  4.68059070e-02  3.48182283e-02  5.27226329e-02  1.23013817e-02\n -4.18945476e-02 -6.26607519e-03  1.32370749e-02 -7.77542517e-02\n -4.54337755e-03 -4.88008596e-02  1.69444960e-02  2.71719303e-02\n -1.57029629e-02 -1.96121205e-02  5.42143025e-02 -1.04829324e-02\n  3.16296905e-07  1.24210063e-02 -2.57157534e-02 -1.33931404e-02\n -1.19198941e-01 -1.78084094e-02 -3.89185809e-02  5.42556271e-02\n  3.01249535e-03 -1.10772792e-02  7.04510976e-03  6.03479780e-02\n -5.55965826e-02  2.31586909e-03 -1.39699960e-02  4.70071360e-02\n  1.19274585e-02 -1.98035035e-02 -2.25390699e-02 -1.16843740e-02\n -4.71997168e-03  8.46915599e-03  3.20675112e-02 -2.62910295e-02\n -5.78418672e-02  2.17882339e-02  1.27821648e-02 -1.26759596e-02\n -5.49275093e-02 -1.70361679e-02 -3.79176624e-02 -2.40866486e-02\n  1.87115707e-02  5.33884168e-02 -4.90637012e-02 -6.83765039e-02\n -4.92588356e-02 -1.83806997e-02 -4.38650511e-03 -6.16047084e-02\n  9.13790427e-03 -5.50733358e-02  5.14619239e-02 -3.02441195e-02\n -3.76122706e-02 -1.21783819e-02 -2.29198672e-02 -5.91069227e-03\n  5.55010289e-02  3.29652391e-02 -2.24245861e-02  6.90928940e-03\n  5.78253064e-03  1.37033360e-02  3.65971550e-02 -1.78678371e-02\n  4.03203554e-02  3.98896709e-02  2.23985706e-02  3.57673615e-02\n -4.60129231e-02 -2.40152795e-02  6.71225321e-03 -5.18196858e-02\n -4.27093953e-02 -5.34029678e-02  7.73340883e-03  2.86279377e-02\n  3.25766402e-34 -5.55941686e-02 -1.86394416e-02 -1.01933756e-03\n -3.24326195e-02  1.46104414e-02  9.13894363e-03 -2.78325398e-02\n  1.92466006e-02 -2.21154597e-02 -2.32136771e-02  1.25690615e-02]'

In [52]:
import numpy as np

np.fromstring(str_emb.strip("[]"), sep=" ")

array([ 6.74242303e-02,  9.02281702e-02, -5.09549305e-03, -3.17545645e-02,
        7.39082247e-02,  3.51976342e-02, -1.97986476e-02,  4.67692316e-02,
        5.35727292e-02,  5.01227845e-03,  3.33928838e-02, -1.62215461e-03,
        1.76080819e-02,  3.62652913e-02, -3.16662947e-04, -1.07117947e-02,
        1.54257547e-02,  2.62176339e-02,  2.77662324e-03,  3.64942662e-02,
       -4.44109626e-02,  1.89362112e-02,  4.90118116e-02,  1.64020602e-02,
       -4.85782735e-02,  3.18290503e-03,  2.72992756e-02, -2.04757787e-03,
       -1.22828595e-02, -7.28049502e-02,  1.20446039e-02,  1.07300067e-02,
        2.10001529e-03, -8.17773119e-02,  2.67830183e-06, -1.81427989e-02,
       -1.20802736e-02,  2.47174520e-02, -6.27467185e-02,  7.35438466e-02,
        2.21624505e-02, -3.28767709e-02, -1.80095714e-02,  2.22952366e-02,
        5.61365113e-02,  1.79513043e-03,  5.25931865e-02, -3.31747695e-03,
       -8.33875965e-03, -1.06284656e-02,  2.31917971e-03, -2.23934688e-02,
       -1.53012108e-02, -9.93055850e-03,  4.65322286e-02,  3.57469432e-02,
       -2.54760254e-02,  2.63694208e-02,  3.74908559e-03, -3.82680483e-02,
        2.58325282e-02,  4.12872806e-02,  2.58181412e-02,  3.32973078e-02,
       -2.51783598e-02,  4.51521464e-02,  4.49088111e-04, -9.96620432e-02,
        4.99491058e-02,  7.13512599e-02,  6.96959272e-02,  3.85235436e-02,
        9.95332841e-03,  4.18640487e-02, -3.22836600e-02, -4.39972244e-03,
        5.05052656e-02, -5.52355759e-02, -2.80108638e-02, -2.27898005e-02,
       -1.71496421e-02,  1.87901538e-02,  1.56440977e-02, -1.39884546e-03,
       -6.59480970e-03,  3.02389562e-02,  6.37047598e-03,  1.96740404e-02,
       -4.15964704e-03, -3.64310890e-02, -1.58165582e-02,  2.32676435e-02,
        2.68640055e-04,  2.17785724e-02,  6.89126877e-03, -2.32419111e-02,
        7.25939795e-02, -5.01198173e-02,  8.08757693e-02, -2.48893499e-02,
        2.90674791e-02,  5.52490167e-02, -9.34375599e-02, -1.32117337e-02,
        1.59285672e-03,  1.37981642e-02,  2.15566717e-02, -3.27911749e-02,
       -2.90928539e-02,  5.62359244e-02, -3.36900190e-03,  8.68975837e-03,
        6.06928952e-04, -1.29652508e-02, -1.35400677e-02,  1.28430333e-02,
       -1.04978811e-02, -4.55567911e-02, -3.67391445e-02, -7.17338175e-02,
        2.54513342e-02,  5.39568849e-02, -2.06747781e-02,  4.84254844e-02,
       -5.90827167e-02,  1.02891870e-01,  2.26163194e-02,  1.03315832e-02,
        1.44357951e-02, -4.90253493e-02, -9.47684050e-03, -2.19099224e-02,
       -2.80026142e-02,  4.23527695e-03, -1.54677290e-03,  1.05041815e-02,
       -6.69239368e-03,  1.90845504e-02,  1.41930496e-02, -5.20690605e-02,
       -6.22595139e-02, -2.99086310e-02, -6.42764568e-02, -2.39539705e-02,
        7.14202598e-02, -1.83041878e-02,  8.09936747e-02, -1.79562513e-02,
        3.72843705e-02,  7.35376328e-02, -2.37267627e-03, -4.52059880e-02,
        4.93059754e-02,  6.30556121e-02,  9.36354175e-02,  8.67178757e-03,
        1.12302259e-04, -3.48906517e-02,  4.02741320e-02,  5.24062812e-02,
        8.55109747e-03, -1.11350244e-04, -8.96978676e-02, -1.52497683e-02,
       -7.32253958e-03,  3.45981643e-02,  1.02752959e-02, -1.70997679e-02,
        1.46063678e-02,  4.21932004e-02, -5.60591929e-02,  3.15297768e-03,
       -1.93180796e-02, -1.37818120e-02,  5.04867770e-02,  3.05518992e-02,
       -4.77813184e-02,  6.20951643e-03,  4.16892841e-02, -1.75102111e-02,
        4.40745912e-02, -7.41178840e-02,  1.78745873e-02,  2.80853041e-04,
       -5.29327802e-02, -8.40260088e-03, -3.77157144e-03, -1.99795086e-02,
        4.42504659e-02, -4.04359922e-02,  3.70720848e-02,  2.28037927e-04,
       -2.61265673e-02, -8.13645944e-02,  7.35088615e-05,  3.39099811e-03,
        8.93966388e-03, -1.79453529e-02,  2.71475632e-02, -7.76860192e-02,
        5.10037094e-02,  2.96539497e-02,  2.64490042e-02, -7.93659419e-04,
       -3.21819074e-02,  3.80366221e-02,  2.37715300e-02, -1.31111825e-02,
        2.00448092e-02, -2.07266561e-03, -5.85778579e-02, -1.51491854e-02,
        4.73964736e-02,  9.37170722e-03, -2.27221586e-02, -3.49049852e-03,
       -1.11097069e-02, -1.73014589e-02,  1.91120859e-02,  7.33278245e-02,
        2.52724867e-02,  2.29908042e-02, -8.63382965e-02, -2.05237642e-02,
       -2.40728613e-02,  7.85169844e-03,  5.92232570e-02, -1.95050165e-02,
        7.27934530e-04,  4.86338772e-02,  3.90096009e-02,  5.45958988e-02,
       -3.78994755e-02,  2.14201622e-02,  2.44414667e-03,  4.14731763e-02,
        7.67865777e-02,  3.91553007e-02, -2.11405847e-02,  4.84219529e-02,
       -5.93219958e-02,  2.98017520e-03, -3.89345512e-02, -3.50046461e-03,
       -6.14648871e-02,  2.82716919e-02, -3.57951298e-02, -2.45329775e-02,
       -6.73675239e-02,  9.39845145e-02,  2.53813528e-02, -8.76086205e-03,
        9.62462183e-03,  1.65698957e-02, -5.34133501e-02, -1.83703005e-02,
       -5.44540286e-02, -5.18859811e-02, -3.99824083e-02,  6.01737648e-02,
       -4.02110331e-02,  3.40260677e-02,  7.12319510e-03, -1.76352486e-02,
        2.63533667e-02, -8.16680342e-02,  4.15973030e-02,  1.10543594e-02,
        7.73297669e-03, -3.55056673e-02, -5.87681588e-03, -1.41534479e-02,
       -2.71463636e-02,  2.38195769e-02, -3.44787771e-03,  3.28347944e-02,
        4.43370547e-03, -3.00127808e-02,  4.79745306e-02, -4.05801013e-02,
       -2.13998370e-02,  7.87418708e-02, -1.56304650e-02,  1.89303067e-02,
        2.67554782e-02, -4.17765640e-02,  6.49793260e-03,  1.60408067e-03,
        6.68079853e-02, -5.28950803e-02,  4.18435931e-02, -5.38789518e-02,
        2.94470470e-02,  1.48594240e-02, -4.29649390e-02,  3.44470292e-02,
       -2.75051333e-02,  1.37509359e-02,  4.09903675e-02, -8.88956897e-03,
       -3.05098691e-03,  3.34398262e-02, -4.04661288e-03,  3.28654051e-02,
       -1.46095185e-02,  2.07155384e-02, -3.05071287e-03, -3.89432386e-02,
        4.88118920e-03, -2.98723225e-02,  1.74396450e-03,  8.60807076e-02,
        6.68614404e-03, -1.62573718e-02, -8.12874641e-03, -3.57048810e-02,
       -4.79689948e-02,  2.25290712e-02,  2.27440670e-02, -1.93761988e-03,
        1.19013004e-02, -1.03209540e-02, -1.32569689e-02, -1.44635225e-02,
       -3.17995809e-03, -2.89135128e-02,  4.88829706e-03,  4.54248637e-02,
       -1.08878419e-01, -4.45946380e-02, -1.69045979e-03,  1.78573783e-02,
        5.74182831e-02, -1.36333192e-02,  2.30217595e-02, -4.61972505e-02,
       -3.12755220e-02,  6.21251715e-03, -4.99114506e-02, -3.68294045e-02,
       -3.47710438e-02,  2.01239600e-03,  3.99565703e-04,  6.69961870e-02,
       -1.72363892e-02, -5.30299619e-02,  9.97220911e-03,  2.38085296e-02,
       -1.78703535e-02,  1.95265561e-02, -5.12357764e-02, -3.79956029e-02,
        2.52402592e-02, -3.15280147e-02,  2.82167550e-02, -1.40533466e-02,
        2.75645517e-02, -7.57218618e-03, -3.13508101e-02, -1.07884558e-03,
        3.08622047e-02,  8.46480727e-02, -2.32757386e-02, -6.32615834e-02,
        6.48503602e-02,  5.11871055e-02, -4.69511282e-03,  2.16896739e-02,
        2.28435379e-02, -1.75960083e-02, -1.76536355e-06,  5.03176525e-02,
       -1.49554238e-02,  1.59846917e-02,  2.32572109e-03, -5.87268211e-02,
        3.70019227e-02,  7.27753043e-02, -3.38272154e-02, -1.87539011e-02,
        4.67500798e-02, -1.55598512e-02,  3.56517769e-02,  9.99829452e-03,
       -2.03129463e-02, -5.68483733e-02, -4.97143790e-02, -2.92548966e-02,
        2.40868051e-02, -4.68073227e-02,  1.05818305e-02,  4.22137370e-03,
       -8.80386494e-03, -2.48464057e-03,  7.10905809e-03, -4.04599402e-03,
        1.78003218e-02, -2.39113551e-02, -6.87355548e-03,  3.71275879e-02,
       -1.40690738e-02, -1.23914592e-02,  3.34878154e-02,  3.99022363e-02,
       -1.66716184e-02,  1.48813054e-02,  3.49213332e-02,  4.19481806e-02,
        4.10648249e-02,  2.83284485e-02,  3.04326639e-02, -2.09015291e-02,
        2.80192606e-02, -5.12436293e-02,  2.03535538e-02, -1.46296564e-02,
       -9.95220151e-03, -2.10910197e-02,  4.48565595e-02, -3.29360366e-02,
       -4.55907695e-02,  4.41765971e-02, -2.76714470e-03,  5.73454089e-02,
       -4.17592842e-03, -2.92153358e-02,  2.77037285e-02, -1.52596897e-02,
       -6.19948208e-02,  2.93321908e-02,  4.48227338e-02,  2.11812127e-02,
       -9.11899004e-03, -3.65736266e-03, -3.88816521e-02,  1.71847213e-02,
        7.24660978e-02, -5.53688258e-02, -4.00997885e-02, -1.95436087e-02,
       -1.30693186e-02,  1.26573974e-02,  4.20498289e-03, -3.15169245e-02,
        9.33311321e-03,  7.58654159e-03,  1.25840707e-02,  3.94737981e-02,
        9.20807421e-02,  3.61451022e-02,  2.13236008e-02,  9.98289883e-03,
       -2.49774624e-02,  4.99336496e-02,  3.23858969e-02, -8.34817591e-04,
        4.27204110e-02, -5.24610057e-02,  1.93347149e-02, -2.21239924e-02,
        4.54791710e-02, -1.27856201e-02, -1.74304023e-02,  2.59035584e-02,
       -2.30377279e-02, -3.11631598e-02,  1.57731678e-02,  2.08224822e-03,
       -3.28662805e-02, -2.62360685e-02, -4.70342860e-02,  5.60605116e-02,
        5.20098675e-03,  1.29133379e-02,  1.79670993e-02, -1.74150057e-02,
       -5.59645407e-02, -1.73937846e-02, -2.74459012e-02,  3.91347595e-02,
       -4.81797243e-03,  2.67288927e-03, -8.50864220e-03, -4.77053337e-02,
        5.87333320e-03,  7.48375431e-03, -3.30419354e-02, -2.74910405e-02,
       -8.25846009e-03, -4.79961820e-02,  1.53875239e-02,  4.05623019e-02,
       -1.79937277e-02, -1.53878834e-02, -5.41522214e-03,  3.67399752e-02,
       -3.17350440e-02, -9.00536962e-03, -1.22322142e-02,  2.12535057e-02,
        1.19459182e-02, -8.74406192e-03,  1.68865100e-02, -1.45980315e-02,
       -3.32913958e-02,  3.64130251e-02, -5.11904955e-02,  7.46199023e-03,
       -3.65407728e-02, -4.26876880e-02, -2.81809084e-02, -1.34026548e-02,
        2.66018566e-02,  2.10149381e-02, -1.68677662e-02, -6.13206737e-02,
       -2.10965145e-03, -2.48019695e-02,  2.22637914e-02,  9.25851241e-03,
       -5.53785544e-03, -5.55743836e-02,  7.05644209e-03, -2.49683131e-02,
       -2.00949833e-02,  6.42916840e-03,  1.39889428e-02, -1.45896850e-02,
       -4.80521061e-02,  8.32006633e-02,  5.49593121e-02,  2.75904033e-02,
       -4.87239053e-03,  4.76308390e-02,  2.18205489e-02, -7.30828196e-03,
       -2.96602864e-02,  3.70682217e-03, -6.46586269e-02, -2.82096323e-02,
        7.46354694e-03, -8.55471268e-02,  1.27533143e-02,  2.84523796e-03,
        1.85691677e-02,  5.43100946e-02, -1.22985572e-01, -7.54426047e-02,
        2.15049163e-02, -1.20498702e-01,  3.25353257e-03, -6.59889658e-04,
        1.99478306e-03, -9.97205637e-03,  5.75397052e-02, -6.96372551e-33,
        3.85706723e-02, -4.36092988e-02,  2.15196759e-02,  1.85362808e-02,
        4.17567044e-02,  2.03666389e-02, -1.15470262e-02, -2.76781097e-02,
       -1.84317399e-02,  8.46618786e-03, -8.76250560e-04,  8.28469812e-04,
        2.27911212e-02, -3.13029811e-02,  2.50838716e-02, -8.73164274e-03,
       -4.67526447e-03, -2.55096927e-02,  5.05392859e-03, -3.37545425e-02,
       -4.94915545e-02,  1.56323891e-02, -6.80953031e-03,  2.48010866e-02,
        3.05012055e-02,  2.15578768e-02,  2.22171377e-02, -1.81512497e-02,
       -5.80374040e-02, -1.70573331e-02,  1.63371060e-02,  2.18999535e-02,
        2.73491833e-02,  3.90386991e-02, -2.33403835e-02, -6.28673062e-02,
        2.03809701e-02, -3.03173754e-02, -3.23167257e-02, -7.20663592e-02,
       -3.86938378e-02, -9.82737727e-03,  2.51085777e-02,  3.67949679e-02,
       -1.72969457e-02,  3.02671231e-02, -1.57558993e-02, -3.97941209e-02,
        2.30327770e-02,  3.11237890e-02, -1.92873012e-02,  1.18442606e-02,
       -4.82675619e-03,  4.07815166e-02,  1.03846833e-03,  1.04635991e-01,
        1.90627854e-02,  8.35709367e-03,  2.53371056e-03, -3.13189765e-03,
       -2.78254058e-02,  1.84029397e-02,  2.07019020e-02,  3.69079113e-02,
        2.74160434e-03, -6.01582080e-02,  2.97910068e-02,  1.89672392e-02,
       -3.44730914e-02,  1.51036624e-02, -3.64224464e-02, -2.45670527e-02,
        1.18608791e-02,  1.51273813e-02, -2.76326332e-02, -8.74801502e-02,
       -1.20377848e-02,  8.14919546e-02,  1.35023976e-04, -7.99897965e-03,
       -8.29238296e-02, -1.49161601e-03,  2.35584099e-02,  7.71071017e-03,
       -4.45612222e-02,  5.73876547e-03, -1.62402578e-02,  7.59660592e-03,
        2.89723580e-03,  3.01373890e-03, -1.80747472e-02, -1.61253046e-02,
        7.45354267e-03,  3.02701797e-02,  5.38823903e-02, -8.83090217e-03,
        4.13308106e-02, -4.52555344e-02,  2.63358876e-02, -2.33413596e-02,
       -5.72936907e-02,  3.07124294e-02,  3.20133977e-02, -2.22796127e-02,
        2.18933504e-02, -8.84479210e-02, -1.64413434e-02, -1.85784381e-02,
        3.18324044e-02, -5.17816097e-02,  1.16167264e-02, -4.08341503e-03,
        4.00550738e-02, -2.35409085e-02, -4.24223319e-02,  1.25499824e-02,
        4.68059070e-02,  3.48182283e-02,  5.27226329e-02,  1.23013817e-02,
       -4.18945476e-02, -6.26607519e-03,  1.32370749e-02, -7.77542517e-02,
       -4.54337755e-03, -4.88008596e-02,  1.69444960e-02,  2.71719303e-02,
       -1.57029629e-02, -1.96121205e-02,  5.42143025e-02, -1.04829324e-02,
        3.16296905e-07,  1.24210063e-02, -2.57157534e-02, -1.33931404e-02,
       -1.19198941e-01, -1.78084094e-02, -3.89185809e-02,  5.42556271e-02,
        3.01249535e-03, -1.10772792e-02,  7.04510976e-03,  6.03479780e-02,
       -5.55965826e-02,  2.31586909e-03, -1.39699960e-02,  4.70071360e-02,
        1.19274585e-02, -1.98035035e-02, -2.25390699e-02, -1.16843740e-02,
       -4.71997168e-03,  8.46915599e-03,  3.20675112e-02, -2.62910295e-02,
       -5.78418672e-02,  2.17882339e-02,  1.27821648e-02, -1.26759596e-02,
       -5.49275093e-02, -1.70361679e-02, -3.79176624e-02, -2.40866486e-02,
        1.87115707e-02,  5.33884168e-02, -4.90637012e-02, -6.83765039e-02,
       -4.92588356e-02, -1.83806997e-02, -4.38650511e-03, -6.16047084e-02,
        9.13790427e-03, -5.50733358e-02,  5.14619239e-02, -3.02441195e-02,
       -3.76122706e-02, -1.21783819e-02, -2.29198672e-02, -5.91069227e-03,
        5.55010289e-02,  3.29652391e-02, -2.24245861e-02,  6.90928940e-03,
        5.78253064e-03,  1.37033360e-02,  3.65971550e-02, -1.78678371e-02,
        4.03203554e-02,  3.98896709e-02,  2.23985706e-02,  3.57673615e-02,
       -4.60129231e-02, -2.40152795e-02,  6.71225321e-03, -5.18196858e-02,
       -4.27093953e-02, -5.34029678e-02,  7.73340883e-03,  2.86279377e-02,
        3.25766402e-34, -5.55941686e-02, -1.86394416e-02, -1.01933756e-03,
       -3.24326195e-02,  1.46104414e-02,  9.13894363e-03, -2.78325398e-02,
        1.92466006e-02, -2.21154597e-02, -2.32136771e-02,  1.25690615e-02])

In [ ]:
text_chunks_and_embeddings_df_load["embedding"] = text_chunks_and_embeddings_df_load["embedding"].apply(
    lambda x: np.fromstring(x.strip("[]"), sep=" ")
)

In [65]:
embeddings = np.stack(text_chunks_and_embeddings_df_load["embedding"].tolist(), axis=0)

embeddings.shape

(1680, 768)

In [66]:
import torch 

embeddings = torch.tensor(embeddings, dtype=torch.float32).to("mps")

embeddings.shape

torch.Size([1680, 768])

In [67]:
embeddings.device

device(type='mps', index=0)

In [61]:
from sentence_transformers import util, SentenceTransformer

embedding_model = SentenceTransformer(model_name_or_path="all-mpnet-base-v2",
                                      device="mps")

/Users/nickol/My Fucking Stuff/machine learning/code/local-rag/venv/lib/python3.10/site-packages/huggingface_hub/file_download.py:949: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(

In [75]:
query = "macronutrient functions"

print(f"Query: {query}")

query_embedding = embedding_model.encode(query, convert_to_tensor=True)

from time import perf_counter as timer

start_time = timer()
dot_scores = util.dot_score(a=query_embedding, b=embeddings)
end_time = timer()

print(f"[INFO] Time taken to get scores on {len(embeddings)} embeddings: {end_time - start_time:.5f} seconds.")

top_results_dot_product = torch.topk(dot_scores, k=5)
top_results_dot_product

Query: macronutrient functions
[INFO] Time taken to get scores on 1680 embeddings: 0.00135 seconds.

torch.return_types.topk(
values=tensor([[0.6843, 0.6717, 0.6517, 0.6493, 0.6478]], device='mps:0'),
indices=tensor([[42, 47, 46, 51, 41]], device='mps:0'))

In [81]:
pages_and_texts[42]

{'page_number': 1,
 'page_char_count': 93,
 'page_word_count': 21,
 'page_sentence_count_raw': 3,
 'page_token_count': 23.25,
 'text': 'PART I  CHAPTER 1. BASIC  CONCEPTS IN NUTRITION  Chapter 1. Basic Concepts in Nutrition  |  1',
 'sentences': ['PART I  CHAPTER 1.',
  'BASIC  CONCEPTS IN NUTRITION  Chapter 1.',
  'Basic Concepts in Nutrition  |  1'],
 'page_sentence_count_spacy': 3,
 'sentence_chunks': [['PART I  CHAPTER 1.',
   'BASIC  CONCEPTS IN NUTRITION  Chapter 1.',
   'Basic Concepts in Nutrition  |  1']],
 'num_chunks': 1}